
let PATCHITER = 0;
let BANKITER = 390;
/*
17,6
Aminet_115  MYSTERORG
17 			6
17,7

22 0
25 4
28 3
36 0
40 6 9 10
45 5
47 5 
48 6
53 0 3
60 2
62 4
63 9
64 9
71 1 2 7
74 0 2
95 0
118 0
119 1
124 0 2
125 0
126 2 3 4 5
127 0
130 0
149 0
171 0 1 2
173 2 3 11 14 18
176 0 1 3
188 2
203 1 7 11
208 0
214 6(!) 
223 0 3 5 9 10 13
257 8 21 23
269 11 14 15 19 20 21 25
319 0
336 0...
341 0 4 9
352 5
389 2
399 0
425 0
*/


const banklist = [
"ANALOG-1.syx",
"ShofukuPt1_KV01A.syx",
"rom1A.syx",
"steinber.syx",
"SynprezFM_03.syx",
"weird1.syx",
"solange2.syx",
"analog1.syx",
"Dexed_01.syx"
];


const ALL_BANKS = [//«
"Aminet_10.syx",
"Aminet_100.syx",
"Aminet_101.syx",
"Aminet_102.syx",
"Aminet_103.syx",
"Aminet_104.syx",
"Aminet_105.syx",
"Aminet_106.syx",
"Aminet_107.syx",
"Aminet_108.syx",
"Aminet_109.syx",
"Aminet_11.syx",
"Aminet_110.syx",
"Aminet_111.syx",
"Aminet_112.syx",
"Aminet_113.syx",
"Aminet_114.syx",
"Aminet_115.syx",
"Aminet_116.syx",
"Aminet_117.syx",
"Aminet_118.syx",
"Aminet_119.syx",
"Aminet_12.syx",
"Aminet_120.syx",
"Aminet_121.syx",
"Aminet_122.syx",
"Aminet_123.syx",
"Aminet_124.syx",
"Aminet_125.syx",
"Aminet_126.syx",
"Aminet_127.syx",
"Aminet_128.syx",
"Aminet_129.syx",
"Aminet_13.syx",
"Aminet_130.syx",
"Aminet_131.syx",
"Aminet_132.syx",
"Aminet_133.syx",
"Aminet_134.syx",
"Aminet_135.syx",
"Aminet_136.syx",
"Aminet_137.syx",
"Aminet_138.syx",
"Aminet_139.syx",
"Aminet_14.syx",
"Aminet_140.syx",
"Aminet_141.syx",
"Aminet_142.syx",
"Aminet_143.syx",
"Aminet_144.syx",
"Aminet_145.syx",
"Aminet_146.syx",
"Aminet_147.syx",
"Aminet_148.syx",
"Aminet_149.syx",
"Aminet_15.syx",
"Aminet_150.syx",
"Aminet_151.syx",
"Aminet_152.syx",
"Aminet_153.syx",
"Aminet_154.syx",
"Aminet_155.syx",
"Aminet_156.syx",
"Aminet_157.syx",
"Aminet_158.syx",
"Aminet_159.syx",
"Aminet_16.syx",
"Aminet_160.syx",
"Aminet_161.syx",
"Aminet_162.syx",
"Aminet_163.syx",
"Aminet_164.syx",
"Aminet_165.syx",
"Aminet_166.syx",
"Aminet_167.syx",
"Aminet_168.syx",
"Aminet_169.syx",
"Aminet_17.syx",
"Aminet_18.syx",
"Aminet_19.syx",
"Aminet_2.syx",
"Aminet_20.syx",
"Aminet_21.syx",
"Aminet_22.syx",
"Aminet_23.syx",
"Aminet_24.syx",
"Aminet_25.syx",
"Aminet_26.syx",
"Aminet_27.syx",
"Aminet_28.syx",
"Aminet_29.syx",
"Aminet_3.syx",
"Aminet_30.syx",
"Aminet_31.syx",
"Aminet_32.syx",
"Aminet_33.syx",
"Aminet_34.syx",
"Aminet_35.syx",
"Aminet_36.syx",
"Aminet_37.syx",
"Aminet_38.syx",
"Aminet_39.syx",
"Aminet_4.syx",
"Aminet_40.syx",
"Aminet_41.syx",
"Aminet_42.syx",
"Aminet_43.syx",
"Aminet_44.syx",
"Aminet_45.syx",
"Aminet_46.syx",
"Aminet_47.syx",
"Aminet_48.syx",
"Aminet_49.syx",
"Aminet_5.syx",
"Aminet_50.syx",
"Aminet_51.syx",
"Aminet_52.syx",
"Aminet_53.syx",
"Aminet_54.syx",
"Aminet_55.syx",
"Aminet_56.syx",
"Aminet_57.syx",
"Aminet_58.syx",
"Aminet_59.syx",
"Aminet_6.syx",
"Aminet_60.syx",
"Aminet_61.syx",
"Aminet_62.syx",
"Aminet_63.syx",
"Aminet_64.syx",
"Aminet_65.syx",
"Aminet_66.syx",
"Aminet_67.syx",
"Aminet_68.syx",
"Aminet_69.syx",
"Aminet_7.syx",
"Aminet_70.syx",
"Aminet_71.syx",
"Aminet_72.syx",
"Aminet_73.syx",
"Aminet_74.syx",
"Aminet_75.syx",
"Aminet_76.syx",
"Aminet_77.syx",
"Aminet_78.syx",
"Aminet_79.syx",
"Aminet_8.syx",
"Aminet_80.syx",
"Aminet_81.syx",
"Aminet_82.syx",
"Aminet_83.syx",
"Aminet_84.syx",
"Aminet_85.syx",
"Aminet_86.syx",
"Aminet_87.syx",
"Aminet_88.syx",
"Aminet_89.syx",
"Aminet_9.syx",
"Aminet_90.syx",
"Aminet_91.syx",
"Aminet_92.syx",
"Aminet_93.syx",
"Aminet_94.syx",
"Aminet_95.syx",
"Aminet_96.syx",
"Aminet_97.syx",
"Aminet_98.syx",
"Aminet_99.syx",
"Atari_7V1.SYX",
"Atari_7V2.SYX",
"Atari_7V3.SYX",
"Atari_7V4.SYX",
"Atari_7V5.SYX",
"Atari_7V6.SYX",
"Atari_7V7.SYX",
"Atari_7V8.SYX",
"Atari_7V9.SYX",
"Atari_AAAHGOOD.SYX",
"Atari_AAHGOOD2.SYX",
"Atari_ANALGSET.SYX",
"Atari_BELGIE.SYX",
"Atari_BELLS1.SYX",
"Atari_BEST03.SYX",
"Atari_Best_of.SYX",
"Atari_Best_of2.SYX",
"Atari_COCKERDX.SYX",
"Atari_COMFAIR.SYX",
"Atari_CREATDX.SYX",
"Atari_Cart1.SYX",
"Atari_DAVE.SYX",
"Atari_DDX64.SYX",
"Atari_DDX_A.SYX",
"Atari_DEMO1_A.SYX",
"Atari_DEMO1_B.SYX",
"Atari_DEMO2_A.SYX",
"Atari_DEMO2_B.SYX",
"Atari_DRUMSDX.SYX",
"Atari_DUITSL.SYX",
"Atari_DX1.SYX",
"Atari_DX64_RM.SYX",
"Atari_DX72MR1.SYX",
"Atari_DX72MR2.SYX",
"Atari_DX7I.SYX",
"Atari_DX7II.SYX",
"Atari_DX7_A0.SYX",
"Atari_DX7_A10.SYX",
"Atari_DX7_A11.SYX",
"Atari_DX7_A12.SYX",
"Atari_DX7_A14.SYX",
"Atari_DX7_A16.SYX",
"Atari_DX7_A2.SYX",
"Atari_DX7_A3.SYX",
"Atari_DX7_A4.SYX",
"Atari_DX7_A5.SYX",
"Atari_DX7_A6.SYX",
"Atari_DX7_A7.SYX",
"Atari_DX7_A8.SYX",
"Atari_DX7_A9.SYX",
"Atari_DX7_AA.SYX",
"Atari_DX7_A_1.SYX",
"Atari_DX7_CPP.SYX",
"Atari_Demo1.syx",
"Atari_Demo2.SYX",
"Atari_EFFDEMO4.SYX",
"Atari_EFFECTEN.SYX",
"Atari_EUGENE1.SYX",
"Atari_EUGENE2.SYX",
"Atari_EXTRA_DX.SYX",
"Atari_GERRY1.SYX",
"Atari_GERRY2.SYX",
"Atari_GERRYCRT.SYX",
"Atari_GUITAAR.SYX",
"Atari_HYPRA_01.SYX",
"Atari_HYPRA_02.SYX",
"Atari_JHGLSP.SYX",
"Atari_MARCEL.SYX",
"Atari_MC.SYX",
"Atari_METMIXDX.SYX",
"Atari_METVELDX.SYX",
"Atari_NEW.SYX",
"Atari_NEWAGE.SYX",
"Atari_OMEGA_DX.SYX",
"Atari_ORCHESTR.SYX",
"Atari_OSTERN87.SYX",
"Atari_PARIS.SYX",
"Atari_PERCDX.SYX",
"Atari_PERCUSSI.SYX",
"Atari_PIANO.SYX",
"Atari_PIANOS.SYX",
"Atari_PPGVOCAL.SYX",
"Atari_PRIVATE.SYX",
"Atari_PRIVEII.SYX",
"Atari_SAMPLED.SYX",
"Atari_SJSU1.SYX",
"Atari_SPECIAL.SYX",
"Atari_SPECIAL1.SYX",
"Atari_SPECIAL2.SYX",
"Atari_SPECIALS.SYX",
"Atari_STRING.SYX",
"Atari_STUDIO.SYX",
"Atari_SYNTHESI.SYX",
"Atari_SYNTHY.SYX",
"Atari_SYST_AA.SYX",
"Atari_SYST_BB.SYX",
"Atari_SYST_CC.SYX",
"Atari_SYST_D.SYX",
"Atari_SYST_EE.SYX",
"Atari_SYST_FF.SYX",
"Atari_SYST_GG.SYX",
"Atari_SYST_HH.SYX",
"Atari_SYST_KK.SYX",
"Atari_SYST_LL.SYX",
"Atari_TEXTURES.SYX",
"Atari_THEOA_DX.SYX",
"Atari_TX1.SYX",
"Atari_TX10.SYX",
"Atari_TX11.SYX",
"Atari_TX11b.SYX",
"Atari_TX12.SYX",
"Atari_TX12b.SYX",
"Atari_TX13.SYX",
"Atari_TX13b.SYX",
"Atari_TX14.SYX",
"Atari_TX15.SYX",
"Atari_TX16.SYX",
"Atari_TX17.SYX",
"Atari_TX18.SYX",
"Atari_TX19.SYX",
"Atari_TX19b.SYX",
"Atari_TX2.SYX",
"Atari_TX20.SYX",
"Atari_TX20b.SYX",
"Atari_TX21.SYX",
"Atari_TX21b.SYX",
"Atari_TX22.SYX",
"Atari_TX22b.SYX",
"Atari_TX23.SYX",
"Atari_TX24.SYX",
"Atari_TX25.SYX",
"Atari_TX26.SYX",
"Atari_TX27.SYX",
"Atari_TX28.SYX",
"Atari_TX3.SYX",
"Atari_TX31.SYX",
"Atari_TX32.SYX",
"Atari_TX34.SYX",
"Atari_TX35.SYX",
"Atari_TX36.SYX",
"Atari_TX4.SYX",
"Atari_TX5.SYX",
"Atari_TX51.SYX",
"Atari_TX52.SYX",
"Atari_TX6b.SYX",
"Atari_TX7.SYX",
"Atari_TX7_1.SYX",
"Atari_TX7_2.SYX",
"Atari_TX7_3.SYX",
"Atari_TX7_4.SYX",
"Atari_TX7b.SYX",
"Atari_TX8.SYX",
"Atari_TX8b.SYX",
"Atari_TX9.SYX",
"Atari_TX9b.SYX",
"Atari_Tim1.SYX",
"Atari_Tx6.syx",
"Atari_VARYFAV1.SYX",
"Atari_YAMAHA.SYX",
"Atari_YAMAHA01.SYX",
"Atari_YAMAHA02.SYX",
"Atari_YAMAHA03.SYX",
"Atari_YAMAHA04.SYX",
"Atari_YAMAHA05.SYX",
"Atari_YAMAHA06.SYX",
"Atari_YAMAHA07.SYX",
"Atari_YAMAHA08.SYX",
"Atari_YAMAHA09.SYX",
"Atari_YAMAHA10.SYX",
"Atari_YAMAHA11.SYX",
"Atari_YAMAHA12.SYX",
"Atari_YAMAHA13.SYX",
"Atari_YAMAHA14.SYX",
"Atari_YAMAHA15.SYX",
"Atari_YAMAHA16.SYX",
"Atari_YAMAHA17.SYX",
"Atari_YAMAHA18.SYX",
"Atari_YAMAHA19.SYX",
"Atari_YAMAHA20.SYX",
"Atari_YAMAHA21.SYX",
"Atari_dxce1.SYX",
"Atari_dxfav1.SYX",
"Atari_dxlib2.SYX",
"Atari_dxlibtos.SYX",
"Atari_dxtx001.SYX",
"Atari_dxtx002.SYX",
"Atari_dxtx003.SYX",
"Atari_dxtx004.SYX",
"Atari_dxtx005.SYX",
"Atari_dxtx006.SYX",
"Atari_dxtx007.SYX",
"Atari_dxtx008.SYX",
"Atari_dxtx009.SYX",
"Atari_dxtx010.SYX",
"Atari_libra_1.SYX",
"Atari_libra_2.SYX",
"Atari_libra_3.SYX",
"CART1A.SYX",
"CART1B.SYX",
"CART2A.SYX",
"CART2B.SYX",
"DX7_1ST_DEMO.SYX",
"DX7_216-A.SYX",
"DX7_216-D.SYX",
"DX7_216-E.SYX",
"DX7_216-F.SYX",
"DX7_216-G.SYX",
"DX7_216-H.SYX",
"DX7_216-I.SYX",
"DX7_216-J.SYX",
"DX7_216-K.SYX",
"DX7_2ND_DEMO.SYX",
"DX7_816-A.SYX",
"DX7_816-B.SYX",
"DX7_816-C.SYX",
"DX7_816-D.SYX",
"DX7_816-G.SYX",
"DX7_816-H.SYX",
"DX7_ARPCOMBO.SYX",
"DX7_Aftrtch_1.syx",
"DX7_Aftrtch_2.syx",
"DX7_Aftrtch_3.syx",
"DX7_BANGERS.SYX",
"DX7_BANKNO1.SYX",
"DX7_BASS1.SYX",
"DX7_BASS3.SYX",
"DX7_BASS_1.SYX",
"DX7_BASS_2.SYX",
"DX7_BASS_3.SYX",
"DX7_BASS_4.SYX",
"DX7_BBANK3.SYX",
"DX7_BBANK4.SYX",
"DX7_BELL1.SYX",
"DX7_BELL_1.SYX",
"DX7_BELL_2.SYX",
"DX7_BELL_3.SYX",
"DX7_BESTBANK.SYX",
"DX7_BOBS_VCS.SYX",
"DX7_BRASS1.SYX",
"DX7_CLAV_1.SYX",
"DX7_CLAV_2.SYX",
"DX7_CLAV_3.SYX",
"DX7_CM1.SYX",
"DX7_CM2.SYX",
"DX7_CM3.SYX",
"DX7_CM5.SYX",
"DX7_COMBOS_1.SYX",
"DX7_DR1.SYX",
"DX7_DR2.SYX",
"DX7_DR3.SYX",
"DX7_DR4.SYX",
"DX7_DRT_1.SYX",
"DX7_DRT_2.SYX",
"DX7_DX-BNK01.SYX",
"DX7_DX-BNK02.SYX",
"DX7_DX-BNK03.SYX",
"DX7_DX-BNK04.SYX",
"DX7_DX-BNK07.SYX",
"DX7_DX-BNK08.SYX",
"DX7_DX-BNK09.SYX",
"DX7_DX-BNK10.SYX",
"DX7_DX-BNK11.SYX",
"DX7_DX-BNK12.SYX",
"DX7_DX-BNK13.SYX",
"DX7_DX-BNK14.SYX",
"DX7_DX-BNK15.SYX",
"DX7_DX-BNK16.SYX",
"DX7_DX54.SYX",
"DX7_DX55.SYX",
"DX7_DX56.SYX",
"DX7_DX58.SYX",
"DX7_DX59.SYX",
"DX7_DX62.SYX",
"DX7_DX65.SYX",
"DX7_DX66.SYX",
"DX7_DX67.SYX",
"DX7_DX68.SYX",
"DX7_DX69.SYX",
"DX7_DX70.SYX",
"DX7_DX71.SYX",
"DX7_DX75.SYX",
"DX7_DX76.SYX",
"DX7_DX77.SYX",
"DX7_DX78.SYX",
"DX7_DX79.SYX",
"DX7_DX7MD1.SYX",
"DX7_DX7MD10.SYX",
"DX7_DX7MD2.SYX",
"DX7_DX7MD3.SYX",
"DX7_DX7MD4.SYX",
"DX7_DX7MD5.SYX",
"DX7_DX7MD6.SYX",
"DX7_DX7MD7.SYX",
"DX7_DX7MD8.SYX",
"DX7_DX7MD9.SYX",
"DX7_DX7PAUL.SYX",
"DX7_DX80.SYX",
"DX7_DX81.SYX",
"DX7_DX82.SYX",
"DX7_DX83.SYX",
"DX7_DX84.SYX",
"DX7_DX85.SYX",
"DX7_DX86.SYX",
"DX7_DX87.SYX",
"DX7_DX88.SYX",
"DX7_DX89.SYX",
"DX7_DX90.SYX",
"DX7_DX91.SYX",
"DX7_DX92.SYX",
"DX7_DX93.SYX",
"DX7_DX94.SYX",
"DX7_DX96.SYX",
"DX7_DX99.SYX",
"DX7_DX9VOICE.SYX",
"DX7_DXH1.SYX",
"DX7_DXH2.SYX",
"DX7_DXH3.SYX",
"DX7_D_TEXTUR.SYX",
"DX7_ET_2232.SYX",
"DX7_ET_BELL2.SYX",
"DX7_ET_EVNTS.SYX",
"DX7_ET_PERC.SYX",
"DX7_ET_TOY.SYX",
"DX7_ET_TX1A.SYX",
"DX7_ET_WEIRD.SYX",
"DX7_E_PIANO1.SYX",
"DX7_E_PIANO2.SYX",
"DX7_E_PIANO3.SYX",
"DX7_FRED.SYX",
"DX7_GUITAR_1.SYX",
"DX7_GUITAR_2.SYX",
"DX7_GUITAR_3.SYX",
"DX7_HARPS1.SYX",
"DX7_INDIADX.SYX",
"DX7_INDSPEV.SYX",
"DX7_INT_ACE.SYX",
"DX7_KNM002.SYX",
"DX7_M3.SYX",
"DX7_MARIMBA1.SYX",
"DX7_MDSF1.SYX",
"DX7_MDSF2.SYX",
"DX7_MDSF3.SYX",
"DX7_MDSF4.SYX",
"DX7_MIM-A.SYX",
"DX7_MIM-B.SYX",
"DX7_MIM-C.SYX",
"DX7_MIM-D.SYX",
"DX7_MIM-E.SYX",
"DX7_MIM-F.SYX",
"DX7_MIM-G.SYX",
"DX7_MIM-H.SYX",
"DX7_MIM-I.SYX",
"DX7_NEWVCS01.SYX",
"DX7_ORGAN_1.SYX",
"DX7_ORGAN_2.SYX",
"DX7_ORGAN_3.SYX",
"DX7_ORGAN_4.SYX",
"DX7_ORIGDXVC.SYX",
"DX7_PAD1.SYX",
"DX7_PASS-C.SYX",
"DX7_PASS-E.SYX",
"DX7_PC1-E.SYX",
"DX7_PC1-I.SYX",
"DX7_PC1-K.SYX",
"DX7_PC1-L.SYX",
"DX7_PC1-M.SYX",
"DX7_PC1-N.SYX",
"DX7_PC1-O.SYX",
"DX7_PC1-P.SYX",
"DX7_PC1-S.SYX",
"DX7_PERCUS_1.SYX",
"DX7_PERCUS_2.SYX",
"DX7_PERCUS_3.SYX",
"DX7_PERCUS_4.SYX",
"DX7_PERCUS_5.SYX",
"DX7_PERCUS_6.SYX",
"DX7_PIANO_1.SYX",
"DX7_PIANO_2.SYX",
"DX7_PIANO_3.SYX",
"DX7_RACK1.SYX",
"DX7_RACK2.SYX",
"DX7_RACK3.SYX",
"DX7_RACK4.SYX",
"DX7_RANDOM1.SYX",
"DX7_RANDOM2.SYX",
"DX7_RCHAN001.SYX",
"DX7_SFX1.SYX",
"DX7_SFX2.SYX",
"DX7_SFX3.SYX",
"DX7_SFX4.SYX",
"DX7_SFX5.SYX",
"DX7_SFX_1.SYX",
"DX7_SFX_2.SYX",
"DX7_SFX_3.SYX",
"DX7_SFX_4.SYX",
"DX7_SFX_5.SYX",
"DX7_SONUS10.SYX",
"DX7_SONUS2.SYX",
"DX7_SONUS3.SYX",
"DX7_SONUS4.SYX",
"DX7_SONUS5.SYX",
"DX7_SONUS6.SYX",
"DX7_SONUS7.SYX",
"DX7_SONUS8.SYX",
"DX7_SONUS9.SYX",
"DX7_SPL-A.SYX",
"DX7_SPL-B.SYX",
"DX7_SPL-C.SYX",
"DX7_SPL-D.SYX",
"DX7_SPL-E.SYX",
"DX7_SPLIT2DX.SYX",
"DX7_SYN1.SYX",
"DX7_SYN2.SYX",
"DX7_SYN3.SYX",
"DX7_SYN4.SYX",
"DX7_SYN5.SYX",
"DX7_SYN6.SYX",
"DX7_SYN7.SYX",
"DX7_SYN8.SYX",
"DX7_SYN9.SYX",
"DX7_TX7-A.SYX",
"DX7_TX7VT5.SYX",
"DX7_TYS-A.SYX",
"DX7_TYS-B.SYX",
"DX7_TYS-C.SYX",
"DX7_TYS-D.SYX",
"DivMas_random1.syx",
"DivMas_random2.syx",
"Dx7_bc_1.syx",
"Dx7_bc_2.syx",
"Dx7_bc_3.syx",
"FUKUDA.SYX",
"Geerdes_C-2.syx",
"GreyMat_2.syx",
"GreyMat_5.syx",
"GreyMat_7.syx",
"Guit_Clav1.syx",
"Guit_Clav2.syx",
"Guit_Clav3.syx",
"Guit_Clav4.syx",
"Guit_Clav5.syx",
"Hitaye_DX125.SYX",
"Hitaye_DX126.SYX",
"Hitaye_DX127.SYX",
"Hitaye_DX128.SYX",
"Hitaye_DX129.SYX",
"Hitaye_DX130.SYX",
"Hitaye_DX131.SYX",
"Hitaye_DX132.SYX",
"Hitaye_DX133.SYX",
"Hitaye_DX134.SYX",
"Hitaye_DX135.SYX",
"Hitaye_DX136.SYX",
"Hitaye_DX137.SYX",
"Hitaye_DX138.SYX",
"Hitaye_DX140.SYX",
"Hitaye_DX141.SYX",
"Hitaye_DX142.SYX",
"Hitaye_DX143.SYX",
"Hitaye_DX144.SYX",
"Hitaye_DX145.SYX",
"Hitaye_DX146.SYX",
"Hitaye_DX147.SYX",
"Hitaye_DX148.SYX",
"Hitaye_DX149.SYX",
"Hitaye_DX50.SYX",
"Hitaye_DX51.SYX",
"Hitaye_DX52.SYX",
"Hitaye_DX53.SYX",
"Hitaye_DX57.SYX",
"Hitaye_DX60.SYX",
"Hitaye_DX61.SYX",
"Hitaye_DX63.SYX",
"Hitaye_DX64.SYX",
"Hitaye_DX72.SYX",
"Hitaye_DX73.SYX",
"Hitaye_DX74.SYX",
"Hitaye_DX95.SYX",
"Hitaye_DX97.SYX",
"Hitaye_DX98.SYX",
"Hitaye_Dx100.syx",
"Hitaye_Dx101.syx",
"Hitaye_Dx103.syx",
"Hitaye_Dx104.syx",
"Hitaye_Dx105.syx",
"Hitaye_Dx106.syx",
"Hitaye_Dx107.syx",
"Hitaye_Dx109.syx",
"Hitaye_Dx110.syx",
"Hitaye_Dx111.syx",
"Hitaye_Dx112.syx",
"Hitaye_Dx113.syx",
"Hitaye_Dx114.syx",
"Hitaye_Dx116.syx",
"Hitaye_Dx117.syx",
"Hitaye_Dx118.syx",
"Hitaye_Dx119.syx",
"Hitaye_Dx120.syx",
"Hitaye_Dx121.syx",
"Hitaye_Dx122.syx",
"Hitaye_Dx123.syx",
"Hitaye_Dx124.syx",
"Hitaye_Dx150.syx",
"HolSnd_ACCPIANO.syx",
"HolSnd_ACORDIAN.syx",
"HolSnd_ANALOG-1.syx",
"HolSnd_ANALOG-2.syx",
"HolSnd_ANALOG-3.syx",
"HolSnd_ANALOG-4.syx",
"HolSnd_ANALOG1A.syx",
"HolSnd_ANALOG1B.syx",
"HolSnd_ANALOG2A.syx",
"HolSnd_ANALOG2B.syx",
"HolSnd_BASS1.syx",
"HolSnd_BASS2.syx",
"HolSnd_BASSMAN.syx",
"HolSnd_BELLS1.syx",
"HolSnd_BELLS2.syx",
"HolSnd_BRASS.syx",
"HolSnd_BRASS1.syx",
"HolSnd_BRASS2.syx",
"HolSnd_BRDRANGE.syx",
"HolSnd_CALLHANK.syx",
"HolSnd_CARLOS.syx",
"HolSnd_CLASSIC1.syx",
"HolSnd_CLAVOR2.syx",
"HolSnd_CLAVS1.syx",
"HolSnd_COUNTRY.syx",
"HolSnd_COWBELL.syx",
"HolSnd_DIGITAL1.syx",
"HolSnd_DIGITAL2.syx",
"HolSnd_DIGITAL3.syx",
"HolSnd_DIGITAL4.syx",
"HolSnd_DIGITAL5.syx",
"HolSnd_DRUMS.syx",
"HolSnd_EFFECTS1.syx",
"HolSnd_EFFECTS2.syx",
"HolSnd_ENSEMBLE.syx",
"HolSnd_EPIANO1.syx",
"HolSnd_EPIANO2.syx",
"HolSnd_FLNGRODE.syx",
"HolSnd_GLASS.syx",
"HolSnd_GOODGRP.syx",
"HolSnd_GRAB-BAG.syx",
"HolSnd_GUITARS.syx",
"HolSnd_HIMNVC.syx",
"HolSnd_I-ROBOT.syx",
"HolSnd_IVRYCITY.syx",
"HolSnd_KOTO.syx",
"HolSnd_LONDON.syx",
"HolSnd_MALLETS1.syx",
"HolSnd_MARS.syx",
"HolSnd_MONEY.syx",
"HolSnd_MONEY2.syx",
"HolSnd_MORSPLTZ.syx",
"HolSnd_MORSYNTH.syx",
"HolSnd_MULTS1.syx",
"HolSnd_MUSICBOX.syx",
"HolSnd_MUSICTRN.syx",
"HolSnd_NEWTEETH.syx",
"HolSnd_ORGANS.syx",
"HolSnd_ORGANS1.syx",
"HolSnd_PERCUSS1.syx",
"HolSnd_PERCUSS2.syx",
"HolSnd_PIKAHORN.syx",
"HolSnd_PIPES.syx",
"HolSnd_PKPOKBLO.syx",
"HolSnd_PLUCKED1.syx",
"HolSnd_PLUCKED2.syx",
"HolSnd_PROHNGN.syx",
"HolSnd_PROPHET.syx",
"HolSnd_REEDS-1.syx",
"HolSnd_ROM3BV.syx",
"HolSnd_ROSNBOW.syx",
"HolSnd_RYTHSECA.syx",
"HolSnd_RYTHSECB.syx",
"HolSnd_SCORPIO.syx",
"HolSnd_SJSU-G.syx",
"HolSnd_SNDEFXA.syx",
"HolSnd_SNDEFXB.syx",
"HolSnd_SOMSPLTZ.syx",
"HolSnd_SPLITZ.syx",
"HolSnd_SPRSPLTA.syx",
"HolSnd_SPRSPLTB.syx",
"HolSnd_STAGS.syx",
"HolSnd_STEVE.syx",
"HolSnd_STINGS1.syx",
"HolSnd_STRINGS.syx",
"HolSnd_STRINGS2.syx",
"HolSnd_STRINGS3.syx",
"HolSnd_STRNGEFX.syx",
"HolSnd_SYN-CITY.syx",
"HolSnd_TOP40A.syx",
"HolSnd_TOP40B.syx",
"HolSnd_TRAMP.syx",
"HolSnd_TX1.syx",
"HolSnd_TX10.syx",
"HolSnd_TX11.syx",
"HolSnd_TX12.syx",
"HolSnd_TX14.syx",
"HolSnd_TX15.syx",
"HolSnd_TX16.syx",
"HolSnd_TX17.syx",
"HolSnd_TX18.syx",
"HolSnd_TX19.syx",
"HolSnd_TX2.syx",
"HolSnd_TX20.syx",
"HolSnd_TX21.syx",
"HolSnd_TX22.syx",
"HolSnd_TX23.syx",
"HolSnd_TX24.syx",
"HolSnd_TX25.syx",
"HolSnd_TX26.syx",
"HolSnd_TX27.syx",
"HolSnd_TX28.syx",
"HolSnd_TX29.syx",
"HolSnd_TX3.syx",
"HolSnd_TX30.syx",
"HolSnd_TX31.syx",
"HolSnd_TX32.syx",
"HolSnd_TX33.syx",
"HolSnd_TX34.syx",
"HolSnd_TX35.syx",
"HolSnd_TX36.syx",
"HolSnd_TX37.syx",
"HolSnd_TX38.syx",
"HolSnd_TX39.syx",
"HolSnd_TX4.syx",
"HolSnd_TX40.syx",
"HolSnd_TX41.syx",
"HolSnd_TX42.syx",
"HolSnd_TX43.syx",
"HolSnd_TX44.syx",
"HolSnd_TX45.syx",
"HolSnd_TX46.syx",
"HolSnd_TX47.syx",
"HolSnd_TX48.syx",
"HolSnd_TX49.syx",
"HolSnd_TX5.syx",
"HolSnd_TX50.syx",
"HolSnd_TX51.syx",
"HolSnd_TX52.syx",
"HolSnd_TX53.syx",
"HolSnd_TX54.syx",
"HolSnd_TX55.syx",
"HolSnd_TX56.syx",
"HolSnd_TX57.syx",
"HolSnd_TX58.syx",
"HolSnd_TX59.syx",
"HolSnd_TX6.syx",
"HolSnd_TX60.syx",
"HolSnd_TX61.syx",
"HolSnd_TX62.syx",
"HolSnd_TX63.syx",
"HolSnd_TX64.syx",
"HolSnd_TX65.syx",
"HolSnd_TX66.syx",
"HolSnd_TX68.syx",
"HolSnd_TX69.syx",
"HolSnd_TX7.syx",
"HolSnd_TX70.syx",
"HolSnd_TX71.syx",
"HolSnd_TX72.syx",
"HolSnd_TX73.syx",
"HolSnd_TX74.syx",
"HolSnd_TX76.syx",
"HolSnd_TX77.syx",
"HolSnd_TX79.syx",
"HolSnd_TX8.syx",
"HolSnd_TX80.syx",
"HolSnd_TX81.syx",
"HolSnd_TX82.syx",
"HolSnd_TX83.syx",
"HolSnd_TX85.syx",
"HolSnd_TX86.syx",
"HolSnd_TX87.syx",
"HolSnd_TX88.syx",
"HolSnd_TX89.syx",
"HolSnd_TX9.syx",
"HolSnd_TX90.syx",
"HolSnd_TX91.syx",
"HolSnd_TX92.syx",
"HolSnd_TX93.syx",
"HolSnd_TX94.syx",
"HolSnd_TX95.syx",
"HolSnd_TX96.syx",
"HolSnd_TX97.syx",
"HolSnd_VARETY.syx",
"HolSnd_VOICES1.syx",
"HolSnd_WDWINDS1.syx",
"HolSnd_WEDING1.syx",
"HolSnd_WEDING2.syx",
"HolSnd_XYLOS-V.syx",
"Inst_2003.SYX",
"Inst_AAAHGOOD.SYX",
"Inst_AAHGOOD2.SYX",
"Inst_ACCORD01.SYX",
"Inst_AEGIX.SYX",
"Inst_AFRICA01.SYX",
"Inst_ANALGSET.SYX",
"Inst_ANALOG01.SYX",
"Inst_ANALOG02.SYX",
"Inst_ANALOG03.SYX",
"Inst_ANALOG04.SYX",
"Inst_ANALOG05.SYX",
"Inst_ANALOG1.SYX",
"Inst_ANALOG3.SYX",
"Inst_ANALOG4.SYX",
"Inst_ANALOG_1.SYX",
"Inst_ANALOG_2.SYX",
"Inst_ANALOG_3.SYX",
"Inst_ASIA01.SYX",
"Inst_ASIA02.SYX",
"Inst_ASIA03.SYX",
"Inst_BANK3.SYX",
"Inst_BANK4.SYX",
"Inst_BASS--06.SYX",
"Inst_BASS--07.SYX",
"Inst_BASS--09.SYX",
"Inst_BASS--10.SYX",
"Inst_BASS--12.SYX",
"Inst_BASS--13.SYX",
"Inst_BASS--14.SYX",
"Inst_BASS--19.SYX",
"Inst_BASS--20.SYX",
"Inst_BASS.syx",
"Inst_BASS001.SYX",
"Inst_BASS002.SYX",
"Inst_BASS003.SYX",
"Inst_BASS004.SYX",
"Inst_BASS005.SYX",
"Inst_BASS006.SYX",
"Inst_BASS007.SYX",
"Inst_BASS008.SYX",
"Inst_BASS009.SYX",
"Inst_BASS010.SYX",
"Inst_BASS011.SYX",
"Inst_BASS012.SYX",
"Inst_BASS013.SYX",
"Inst_BASS014.SYX",
"Inst_BASS015.SYX",
"Inst_BASS016.SYX",
"Inst_BASS018.SYX",
"Inst_BASS019.SYX",
"Inst_BASS020.SYX",
"Inst_BASS021.SYX",
"Inst_BASS022.SYX",
"Inst_BASS023.SYX",
"Inst_BASS024.SYX",
"Inst_BASS025.SYX",
"Inst_BASS1.syx",
"Inst_BASS3.SYX",
"Inst_BASS_01.SYX",
"Inst_BASS_02.SYX",
"Inst_BASS_03.SYX",
"Inst_BASS_04.SYX",
"Inst_BASS_05.SYX",
"Inst_BASS_06.SYX",
"Inst_BASS_07.SYX",
"Inst_BASS_08.SYX",
"Inst_BASS_09.SYX",
"Inst_BASS_1.SYX",
"Inst_BASS_10.SYX",
"Inst_BASS_11.SYX",
"Inst_BASS_12.SYX",
"Inst_BASS_13.SYX",
"Inst_BASS_14.SYX",
"Inst_BASS_15.SYX",
"Inst_BASS_2.SYX",
"Inst_BASS_3.SYX",
"Inst_BASS_4.SYX",
"Inst_BELL01.SYX",
"Inst_BELL02.SYX",
"Inst_BELL03.SYX",
"Inst_BELL04.SYX",
"Inst_BELL05.SYX",
"Inst_BELL1.SYX",
"Inst_BELLS_01.SYX",
"Inst_BELLS_02.SYX",
"Inst_BELLS_03.SYX",
"Inst_BELLTEL.SYX",
"Inst_BELL_1.SYX",
"Inst_BELL_2.SYX",
"Inst_BELL_3.SYX",
"Inst_BOTOP40A.SYX",
"Inst_BRASS-01.SYX",
"Inst_BRASS-08.SYX",
"Inst_BRASS-13.SYX",
"Inst_BRASS-14.SYX",
"Inst_BRASS-20.SYX",
"Inst_BRASS001.SYX",
"Inst_BRASS002.SYX",
"Inst_BRASS003.SYX",
"Inst_BRASS004.SYX",
"Inst_BRASS005.SYX",
"Inst_BRASS006.SYX",
"Inst_BRASS007.SYX",
"Inst_BRASS008.SYX",
"Inst_BRASS009.SYX",
"Inst_BRASS010.SYX",
"Inst_BRASS011.SYX",
"Inst_BRASS012.SYX",
"Inst_BRASS013.SYX",
"Inst_BRASS014.SYX",
"Inst_BRASS015.SYX",
"Inst_BRASS016.SYX",
"Inst_BRASS017.SYX",
"Inst_BRASS018.SYX",
"Inst_BRASS019.SYX",
"Inst_BRASS020.SYX",
"Inst_BRASS021.SYX",
"Inst_BRASS022.SYX",
"Inst_BRASS_01.SYX",
"Inst_BRASS_02.SYX",
"Inst_BRASS_03.SYX",
"Inst_BRASS_04.SYX",
"Inst_BRASS_05.SYX",
"Inst_BRASS_06.SYX",
"Inst_BRASS_07.SYX",
"Inst_BRASS_08.SYX",
"Inst_BRASS_09.SYX",
"Inst_BRASS_10.SYX",
"Inst_BRASS_11.SYX",
"Inst_BRASS_12.SYX",
"Inst_BRASS_13.SYX",
"Inst_BRASS_14.SYX",
"Inst_BRASS_15.SYX",
"Inst_BRASS_16.SYX",
"Inst_BRASS_17.SYX",
"Inst_BRASS_18.SYX",
"Inst_Bank0009.syx",
"Inst_Bank0043.syx",
"Inst_Bank0044.syx",
"Inst_Bank0047.syx",
"Inst_Bank0048.syx",
"Inst_Bank0054.syx",
"Inst_Basses1.SYX",
"Inst_Basses2.SYX",
"Inst_Best_of2.SYX",
"Inst_Brass1a.SYX",
"Inst_Brass2a.SYX",
"Inst_Brass3.syx",
"Inst_C-LAB_1.SYX",
"Inst_CELLO01.SYX",
"Inst_CELLO02.SYX",
"Inst_CELLO03.SYX",
"Inst_CHIMES2.SYX",
"Inst_CHIMES3.SYX",
"Inst_CHIMES4.SYX",
"Inst_CHIMES5.SYX",
"Inst_CHOIR01.SYX",
"Inst_CHOIR02.SYX",
"Inst_CHOIR03.SYX",
"Inst_CHOIR04.SYX",
"Inst_CHROMA01.SYX",
"Inst_CHROMA15.SYX",
"Inst_CHRPER01.SYX",
"Inst_CHRPER02.SYX",
"Inst_CHRPER03.SYX",
"Inst_CHRPER04.SYX",
"Inst_CHRPER05.SYX",
"Inst_CHRPER06.SYX",
"Inst_CHRPER07.SYX",
"Inst_CHRPER08.SYX",
"Inst_CHRPER09.SYX",
"Inst_CHRPER10.SYX",
"Inst_CHURCH01.SYX",
"Inst_CHURCH02.SYX",
"Inst_CHURCH03.SYX",
"Inst_CLAV01.SYX",
"Inst_CLAV02.SYX",
"Inst_CLAV03.SYX",
"Inst_CLAV04.SYX",
"Inst_CLAV05.SYX",
"Inst_CLAV06.SYX",
"Inst_CLAV07.SYX",
"Inst_CLAV08.SYX",
"Inst_CLAV1.SYX",
"Inst_CLAVS.SYX",
"Inst_CLAV_1.SYX",
"Inst_CLAV_2.SYX",
"Inst_CLAV_3.SYX",
"Inst_CLSSIC01.SYX",
"Inst_CZEISZPE.SYX",
"Inst_Cart1.SYX",
"Inst_Choir.SYX",
"Inst_DAVE1.SYX",
"Inst_DDX64.SYX",
"Inst_DECKARD.SYX",
"Inst_DEMO5.SYX",
"Inst_DIVERS.SYX",
"Inst_DRT1.SYX",
"Inst_DRT2.SYX",
"Inst_DRUMS01.SYX",
"Inst_DRUMS02.SYX",
"Inst_DRUMS03.SYX",
"Inst_DRUMS04.SYX",
"Inst_DRUMS05.SYX",
"Inst_DRUMS06.SYX",
"Inst_DRUMS07.SYX",
"Inst_DRUMS08.SYX",
"Inst_DRUMS09.SYX",
"Inst_DRUMS10.SYX",
"Inst_DRUMS11.SYX",
"Inst_DRUMS12.SYX",
"Inst_DX1.SYX",
"Inst_DX125.SYX",
"Inst_DX135.SYX",
"Inst_DX137.SYX",
"Inst_DX138.SYX",
"Inst_DX140.SYX",
"Inst_DX141.SYX",
"Inst_DX142.SYX",
"Inst_DX147.SYX",
"Inst_DX148.SYX",
"Inst_DX149.SYX",
"Inst_DX64.SYX",
"Inst_DX64_RM.SYX",
"Inst_DX72MR2.SYX",
"Inst_DX7I.SYX",
"Inst_DX7II.SYX",
"Inst_DX7ROM1A.SYX",
"Inst_DX7ROM2A.SYX",
"Inst_DX7ROM2B.SYX",
"Inst_DX7RhodesEtc.syx",
"Inst_DX7_A11.SYX",
"Inst_DX7_A12.SYX",
"Inst_DX7_A14.SYX",
"Inst_DX7_A16.SYX",
"Inst_DX7_A2.SYX",
"Inst_DX7_A4.SYX",
"Inst_DX7_A6.SYX",
"Inst_DX7_A7.SYX",
"Inst_DX7_AA.SYX",
"Inst_DX7_A_1.SYX",
"Inst_DX7_CPP.SYX",
"Inst_DX9.SYX",
"Inst_DX95.SYX",
"Inst_DX97.SYX",
"Inst_Drm2.syx",
"Inst_Drm2a.syx",
"Inst_Drmoct.syx",
"Inst_Dx101.syx",
"Inst_Dx103.syx",
"Inst_Dx106.syx",
"Inst_Dx107.syx",
"Inst_Dx111.syx",
"Inst_Dx112.syx",
"Inst_Dx113.syx",
"Inst_Dx114.syx",
"Inst_Dx119.syx",
"Inst_Dx120.syx",
"Inst_Dx121.syx",
"Inst_Dx122.syx",
"Inst_Dx150.syx",
"Inst_Dx7_0628.syx",
"Inst_Dxorgans.syx",
"Inst_EFFDEMO4.SYX",
"Inst_EFFECT-2.SYX",
"Inst_EFFECT01.SYX",
"Inst_EFFECT02.SYX",
"Inst_EFFECT03.SYX",
"Inst_EFFECT04.SYX",
"Inst_EFFECT05.SYX",
"Inst_EFFECT06.SYX",
"Inst_EFFECT07.SYX",
"Inst_EFFECT08.SYX",
"Inst_EFFECT09.SYX",
"Inst_EFFECT10.SYX",
"Inst_EFFECT11.SYX",
"Inst_EFFECT12.SYX",
"Inst_EFFECT13.SYX",
"Inst_EFFECT14.SYX",
"Inst_EFFECT15.SYX",
"Inst_EFFECT16.SYX",
"Inst_EFFECT17.SYX",
"Inst_EFFECT18.SYX",
"Inst_EFFECT19.SYX",
"Inst_EFFECT20.SYX",
"Inst_EFFECTS1.SYX",
"Inst_EFFECTS2.SYX",
"Inst_EFFECTS3.SYX",
"Inst_EFFECTS4.SYX",
"Inst_EFFECTS5.SYX",
"Inst_EFFECTS6.SYX",
"Inst_EFFECTS7.SYX",
"Inst_EFFECTS8.SYX",
"Inst_EFX.SYX",
"Inst_EP01.SYX",
"Inst_EP02.SYX",
"Inst_EP03.SYX",
"Inst_EP04.SYX",
"Inst_EP05.SYX",
"Inst_EP06.SYX",
"Inst_EP07.SYX",
"Inst_EP08.SYX",
"Inst_EP09.SYX",
"Inst_EP10.SYX",
"Inst_EP11.SYX",
"Inst_EP12.SYX",
"Inst_EPiano1.syx",
"Inst_EPiano2.syx",
"Inst_ET_2232.SYX",
"Inst_ET_BELL2.SYX",
"Inst_ET_EVNTS.SYX",
"Inst_ET_PERC.SYX",
"Inst_ET_TOY.SYX",
"Inst_ET_TX1A.SYX",
"Inst_ET_WEIRD.SYX",
"Inst_EUROPE01.SYX",
"Inst_EXTRA_DX.SYX",
"Inst_E_PIANO1.SYX",
"Inst_E_PIANO2.SYX",
"Inst_E_PIANO3.SYX",
"Inst_Effect-1.syx",
"Inst_Eorgan1b.syx",
"Inst_Eorgan1c.syx",
"Inst_Ethnic.syx",
"Inst_F1.syx",
"Inst_FATSTUFF.SYX",
"Inst_FLUTE.SYX",
"Inst_FLUTE01.SYX",
"Inst_FLUTE02.SYX",
"Inst_FLUTE03.SYX",
"Inst_FLUTE04.SYX",
"Inst_FLUTE05.SYX",
"Inst_FLUTE06.SYX",
"Inst_FLUTE07.SYX",
"Inst_FMSYNT2.syx",
"Inst_Fx1.SYX",
"Inst_GTRSONUS.SYX",
"Inst_GTRS_01.SYX",
"Inst_GTRS_A-D.SYX",
"Inst_GTRS_D.SYX",
"Inst_GTRS_EL.SYX",
"Inst_GTRS_G-J.SYX",
"Inst_GTRS_J-K.SYX",
"Inst_GTRS_L-N.SYX",
"Inst_GTRS_N-R.SYX",
"Inst_GTRS_S-V.SYX",
"Inst_GUITAR-01.SYX",
"Inst_GUITAR01.SYX",
"Inst_GUITAR02.SYX",
"Inst_GUITAR03.SYX",
"Inst_GUITAR04.SYX",
"Inst_GUITAR05.SYX",
"Inst_GUITAR06.SYX",
"Inst_GUITAR07.SYX",
"Inst_GUITAR08.SYX",
"Inst_GUITAR09.SYX",
"Inst_GUITAR1.SYX",
"Inst_GUITAR2.SYX",
"Inst_GUITARS.SYX",
"Inst_GUITAR_1.SYX",
"Inst_GUITAR_2.SYX",
"Inst_GUITAR_3.SYX",
"Inst_Gtrs.SYX",
"Inst_Guitars.syx",
"Inst_HARMONIC.SYX",
"Inst_HARP01.SYX",
"Inst_HARP02.SYX",
"Inst_HARP03.SYX",
"Inst_HARPS1.SYX",
"Inst_HYPRA_01.SYX",
"Inst_Harpbell.SYX",
"Inst_INDIADX.SYX",
"Inst_INT2.SYX",
"Inst_INT3.SYX",
"Inst_INTSYNTO.syx",
"Inst_Italian2.syx",
"Inst_Italian3.syx",
"Inst_K1.SYX",
"Inst_KEYBDS01.SYX",
"Inst_KEYPLUC.syx",
"Inst_KING.SYX",
"Inst_KOTO.SYX",
"Inst_Keybd01.syx",
"Inst_Keybd02.syx",
"Inst_Keyboard.syx",
"Inst_Keys.syx",
"Inst_LASER.SYX",
"Inst_LATIN.SYX",
"Inst_LEAD01.SYX",
"Inst_LEAD02.SYX",
"Inst_LEAD03.SYX",
"Inst_Lead01S.syx",
"Inst_Lead02S.syx",
"Inst_Lead03S.syx",
"Inst_MALLETS1.SYX",
"Inst_MALLETS2.SYX",
"Inst_MARCEL.SYX",
"Inst_MARIMB01.SYX",
"Inst_MARIMB02.SYX",
"Inst_MARIMBA1.SYX",
"Inst_METVELDX.SYX",
"Inst_MISC_01.SYX",
"Inst_MISC_02.SYX",
"Inst_MISC_03.SYX",
"Inst_MISC_04.SYX",
"Inst_MISC_05.SYX",
"Inst_MISC_06.SYX",
"Inst_MISC_07.SYX",
"Inst_MISC_08.SYX",
"Inst_MISC_09.SYX",
"Inst_MISC_10.SYX",
"Inst_MISC_11.SYX",
"Inst_MISC_12.SYX",
"Inst_MISC_13.SYX",
"Inst_MISC_14.SYX",
"Inst_MISC_15.SYX",
"Inst_MISC_16.SYX",
"Inst_MISC_17.SYX",
"Inst_MISC_18.SYX",
"Inst_MISC_19.SYX",
"Inst_MISC_20.SYX",
"Inst_MISC_21.SYX",
"Inst_MISC_22.SYX",
"Inst_MISC_23.SYX",
"Inst_MISC_24.SYX",
"Inst_MISC_25.SYX",
"Inst_MISC_26.SYX",
"Inst_MISC_27.SYX",
"Inst_MISC_28.SYX",
"Inst_MISC_29.SYX",
"Inst_MISC_30.SYX",
"Inst_MISC_31.SYX",
"Inst_MISC_32.SYX",
"Inst_MISC_33.SYX",
"Inst_MISC_34.SYX",
"Inst_MONTELEO.SYX",
"Inst_MOOG.SYX",
"Inst_MOOG8A.SYX",
"Inst_MORTEGA.SYX",
"Inst_More_key.syx",
"Inst_NEWAGE.SYX",
"Inst_OBOEBASS.SYX",
"Inst_OBRHEIM4.SYX",
"Inst_ORCH01.SYX",
"Inst_ORCH02.SYX",
"Inst_ORCH03.SYX",
"Inst_ORCH04.SYX",
"Inst_ORCHESTR.SYX",
"Inst_ORCH_1.SYX",
"Inst_ORGAN-35.SYX",
"Inst_ORGAN-36.SYX",
"Inst_ORGAN-40.SYX",
"Inst_ORGAN01.SYX",
"Inst_ORGAN02.SYX",
"Inst_ORGAN03.SYX",
"Inst_ORGAN04.SYX",
"Inst_ORGAN05.SYX",
"Inst_ORGAN06.SYX",
"Inst_ORGAN07.SYX",
"Inst_ORGAN08.SYX",
"Inst_ORGAN09.SYX",
"Inst_ORGAN1.SYX",
"Inst_ORGAN10.SYX",
"Inst_ORGAN11.SYX",
"Inst_ORGAN12.SYX",
"Inst_ORGAN13.SYX",
"Inst_ORGAN14.SYX",
"Inst_ORGAN2.SYX",
"Inst_ORGAN3.SYX",
"Inst_ORGAN_05.SYX",
"Inst_ORGAN_1.SYX",
"Inst_ORGAN_2.SYX",
"Inst_ORGAN_3.SYX",
"Inst_ORGAN_4.SYX",
"Inst_ORGTAP.syx",
"Inst_ORG_CLAV.SYX",
"Inst_Obrheim5.syx",
"Inst_Orchestra10.SYX",
"Inst_Orchestra2.syx",
"Inst_Orchestra4.syx",
"Inst_Orchestra7.SYX",
"Inst_Orchestra8.SYX",
"Inst_Orchestra9.SYX",
"Inst_Organ3.syx",
"Inst_PAD1.SYX",
"Inst_PADS01.SYX",
"Inst_PADS02.SYX",
"Inst_PADS03.SYX",
"Inst_PADS04.SYX",
"Inst_PADS05.SYX",
"Inst_PARTIAL.SYX",
"Inst_PATCHES.SYX",
"Inst_PEARSON.SYX",
"Inst_PEDANNA.SYX",
"Inst_PERC01.SYX",
"Inst_PERC02.SYX",
"Inst_PERC1.SYX",
"Inst_PERC2.SYX",
"Inst_PERCUS04.SYX",
"Inst_PERCUS05.SYX",
"Inst_PERCUS06.SYX",
"Inst_PERCUS07.SYX",
"Inst_PERCUS08.SYX",
"Inst_PERCUS09.SYX",
"Inst_PERCUS10.SYX",
"Inst_PERCUSS.SYX",
"Inst_PERCUSSI.SYX",
"Inst_PERCUS_1.SYX",
"Inst_PERCUS_2.SYX",
"Inst_PERCUS_3.SYX",
"Inst_PERCUS_4.SYX",
"Inst_PERCUS_5.SYX",
"Inst_PERCUS_6.SYX",
"Inst_PERCVIBE.SYX",
"Inst_PERC_A.SYX",
"Inst_PERC_B.SYX",
"Inst_PERSONUS.SYX",
"Inst_PIANO-11.SYX",
"Inst_PIANO-12.SYX",
"Inst_PIANO.SYX",
"Inst_PIANO01.SYX",
"Inst_PIANO02.SYX",
"Inst_PIANO03.SYX",
"Inst_PIANO04.SYX",
"Inst_PIANO05.SYX",
"Inst_PIANO06.SYX",
"Inst_PIANO07.SYX",
"Inst_PIANO08.SYX",
"Inst_PIANO09.SYX",
"Inst_PIANO1.SYX",
"Inst_PIANO10.SYX",
"Inst_PIANO11.SYX",
"Inst_PIANO12.SYX",
"Inst_PIANO13.SYX",
"Inst_PIANO14.SYX",
"Inst_PIANO15.SYX",
"Inst_PIANO16.SYX",
"Inst_PIANO17.SYX",
"Inst_PIANO18.SYX",
"Inst_PIANO19.SYX",
"Inst_PIANO20.SYX",
"Inst_PIANO21.SYX",
"Inst_PIANO22.SYX",
"Inst_PIANO23.SYX",
"Inst_PIANO24.SYX",
"Inst_PIANO25.SYX",
"Inst_PIANO32.SYX",
"Inst_PIANODX7.SYX",
"Inst_PIANOS.SYX",
"Inst_PIANO_02.SYX",
"Inst_PIANO_03.SYX",
"Inst_PIANO_04.SYX",
"Inst_PIANO_05.SYX",
"Inst_PIANO_06.SYX",
"Inst_PIANO_07.SYX",
"Inst_PIANO_08.SYX",
"Inst_PIANO_09.SYX",
"Inst_PIANO_1.SYX",
"Inst_PIANO_10.SYX",
"Inst_PIANO_11.SYX",
"Inst_PIANO_12.SYX",
"Inst_PIANO_13.SYX",
"Inst_PIANO_2.SYX",
"Inst_PIANO_3.SYX",
"Inst_PIANO_A1.SYX",
"Inst_PIANO_E1.SYX",
"Inst_PIANO_E2.SYX",
"Inst_PIANO_E3.SYX",
"Inst_PIANO_E4.SYX",
"Inst_PIANO_E5.SYX",
"Inst_PIZZ01.SYX",
"Inst_PLUCKED.SYX",
"Inst_POWERPLY.SYX",
"Inst_PR01.SYX",
"Inst_PR02.SYX",
"Inst_PR03.SYX",
"Inst_PRO2.SYX",
"Inst_PROPHET5.SYX",
"Inst_Perc.SYX",
"Inst_Percorg.syx",
"Inst_Percorg2.syx",
"Inst_Pianos2.SYX",
"Inst_Plucked4.syx",
"Inst_Plucked5.syx",
"Inst_Plucked6.SYX",
"Inst_RAMBANK1.SYX",
"Inst_RAMCART.SYX",
"Inst_RAMCARTP.SYX",
"Inst_RAMCARTR.SYX",
"Inst_RAMNBANK.SYX",
"Inst_RAM_BANK.SYX",
"Inst_RESONA01.SYX",
"Inst_RESONA02.SYX",
"Inst_RESONA03.SYX",
"Inst_RESONA04.SYX",
"Inst_RHODES01.SYX",
"Inst_RHODES02.SYX",
"Inst_RHODES03.SYX",
"Inst_RHODES04.SYX",
"Inst_RHODES1.SYX",
"Inst_RHODES2.SYX",
"Inst_RHODES73.SYX",
"Inst_RLEGNINI.SYX",
"Inst_RM0001.SYX",
"Inst_ROAD1.SYX",
"Inst_ROAD2.SYX",
"Inst_ROM1A.SYX",
"Inst_ROM1B.SYX",
"Inst_ROM2A.SYX",
"Inst_ROM2B.SYX",
"Inst_ROM3A.SYX",
"Inst_ROM3B.SYX",
"Inst_ROM4A.SYX",
"Inst_ROM4B.SYX",
"Inst_Rhodes4.syx",
"Inst_SAX01.SYX",
"Inst_SAX02.SYX",
"Inst_SAX_01.SYX",
"Inst_SAX_02.SYX",
"Inst_SITAR.SYX",
"Inst_SJSU-E.SYX",
"Inst_SJSU-F.SYX",
"Inst_SJSU-G.SYX",
"Inst_SONUS1.SYX",
"Inst_SPACE01.SYX",
"Inst_SPLIT2DX.SYX",
"Inst_SPLITS.SYX",
"Inst_STARMA.SYX",
"Inst_STEPH1.SYX",
"Inst_STEPH2.SYX",
"Inst_STEPH3.SYX",
"Inst_STEPH4.SYX",
"Inst_STEVE.SYX",
"Inst_STEVE1.SYX",
"Inst_STRGS.SYX",
"Inst_STRING01.SYX",
"Inst_STRING02.SYX",
"Inst_STRING03.SYX",
"Inst_STRING04.SYX",
"Inst_STRING05.SYX",
"Inst_STRING06.SYX",
"Inst_STRING07.SYX",
"Inst_STRING08.SYX",
"Inst_STRING09.SYX",
"Inst_STRING1.SYX",
"Inst_STRING10.SYX",
"Inst_STRING11.SYX",
"Inst_STRING12.SYX",
"Inst_STRING13.SYX",
"Inst_STRING14.SYX",
"Inst_STRING15.SYX",
"Inst_STRING16.SYX",
"Inst_STRING17.SYX",
"Inst_STRING18.SYX",
"Inst_STRING19.SYX",
"Inst_STRING2.SYX",
"Inst_STRING20.SYX",
"Inst_STRING32.SYX",
"Inst_STRINGB.SYX",
"Inst_STRINGS.SYX",
"Inst_STUDIO.SYX",
"Inst_SUPERDX.SYX",
"Inst_SUSTAIN1.SYX",
"Inst_SYDRTY01.SYX",
"Inst_SYN5.SYX",
"Inst_SYNBRA01.SYX",
"Inst_SYNBRA02.SYX",
"Inst_SYNCIOP1.SYX",
"Inst_SYNCIOP2.SYX",
"Inst_SYNDR01.SYX",
"Inst_SYNDR02.SYX",
"Inst_SYNPERC1.SYX",
"Inst_SYNPERC2.SYX",
"Inst_SYNPLUS.SYX",
"Inst_SYNSTR01.SYX",
"Inst_SYNSTR02.SYX",
"Inst_SYNSTR03.SYX",
"Inst_SYNSTR04.SYX",
"Inst_SYNSTR05.SYX",
"Inst_SYNSTR06.SYX",
"Inst_SYNTH-06.SYX",
"Inst_SYNTH001.SYX",
"Inst_SYNTH002.SYX",
"Inst_SYNTH003.SYX",
"Inst_SYNTH004.SYX",
"Inst_SYNTH005.SYX",
"Inst_SYNTH006.SYX",
"Inst_SYNTH008.SYX",
"Inst_SYNTH009.SYX",
"Inst_SYNTH010.SYX",
"Inst_SYNTH011.SYX",
"Inst_SYNTH012.SYX",
"Inst_SYNTH013.SYX",
"Inst_SYNTH014.SYX",
"Inst_SYNTH015.SYX",
"Inst_SYNTH016.SYX",
"Inst_SYNTH017.SYX",
"Inst_SYNTH018.SYX",
"Inst_SYNTH019.SYX",
"Inst_SYNTH020.SYX",
"Inst_SYNTH021.SYX",
"Inst_SYNTH022.SYX",
"Inst_SYNTH023.SYX",
"Inst_SYNTH024.SYX",
"Inst_SYNTH025.SYX",
"Inst_SYNTH026.SYX",
"Inst_SYNTH027.SYX",
"Inst_SYNTH028.SYX",
"Inst_SYNTH029.SYX",
"Inst_SYNTH030.SYX",
"Inst_SYNTH031.SYX",
"Inst_SYNTH032.SYX",
"Inst_SYNTH033.SYX",
"Inst_SYNTH034.SYX",
"Inst_SYNTH035.SYX",
"Inst_SYNTH036.SYX",
"Inst_SYNTH037.SYX",
"Inst_SYNTH038.SYX",
"Inst_SYNTH039.SYX",
"Inst_SYNTH040.SYX",
"Inst_SYNTH041.SYX",
"Inst_SYNTH042.SYX",
"Inst_SYNTH043.SYX",
"Inst_SYNTH044.SYX",
"Inst_SYNTH045.SYX",
"Inst_SYNTH046.SYX",
"Inst_SYNTH047.SYX",
"Inst_SYNTH048.SYX",
"Inst_SYNTH049.SYX",
"Inst_SYNTH050.SYX",
"Inst_SYNTH051.SYX",
"Inst_SYNTH052.SYX",
"Inst_SYNTH053.SYX",
"Inst_SYNTH054.SYX",
"Inst_SYNTH055.SYX",
"Inst_SYNTH056.SYX",
"Inst_SYNTH057.SYX",
"Inst_SYNTH058.SYX",
"Inst_SYNTH059.SYX",
"Inst_SYNTH060.SYX",
"Inst_SYNTH061.SYX",
"Inst_SYNTH062.SYX",
"Inst_SYNTH063.SYX",
"Inst_SYNTH064.SYX",
"Inst_SYNTH065.SYX",
"Inst_SYNTH066.SYX",
"Inst_SYNTH067.SYX",
"Inst_SYNTH068.SYX",
"Inst_SYNTH069.SYX",
"Inst_SYNTH070.SYX",
"Inst_SYNTH071.SYX",
"Inst_SYNTH072.SYX",
"Inst_SYNTH073.SYX",
"Inst_SYNTH074.SYX",
"Inst_SYNTH075.SYX",
"Inst_SYNTH076.SYX",
"Inst_SYNTH077.SYX",
"Inst_SYNTHS32.SYX",
"Inst_SYNTHSBN.SYX",
"Inst_SYNTH_01.SYX",
"Inst_SYNTH_02.SYX",
"Inst_SYNTH_03.SYX",
"Inst_SYNTH_04.SYX",
"Inst_SYNTH_05.SYX",
"Inst_SYNTH_06.SYX",
"Inst_SYNTH_07.SYX",
"Inst_SYNTH_08.SYX",
"Inst_SYNTH_09.SYX",
"Inst_SYNTH_10.SYX",
"Inst_SYNTH_11.SYX",
"Inst_SYNTH_12.SYX",
"Inst_SYNTH_13.SYX",
"Inst_SYNTH_14.SYX",
"Inst_SYNTH_15.SYX",
"Inst_SYNTH_16.SYX",
"Inst_SYNTH_17.SYX",
"Inst_SYNTH_18.SYX",
"Inst_SYNTH_19.SYX",
"Inst_SYNTH_20.SYX",
"Inst_SYNTH_21.SYX",
"Inst_SYNTH_22.SYX",
"Inst_SYN_PLUS.SYX",
"Inst_SYST_AA.SYX",
"Inst_SYST_BB.SYX",
"Inst_SYST_CC.SYX",
"Inst_SYST_D.SYX",
"Inst_SYST_EE.SYX",
"Inst_SYST_GG.SYX",
"Inst_Splitsbn.syx",
"Inst_Strings1.SYX",
"Inst_Strings2.SYX",
"Inst_Synths.syx",
"Inst_Synths1.SYX",
"Inst_Synths2.SYX",
"Inst_Synths3.SYX",
"Inst_Synths4.SYX",
"Inst_TEXTURES.SYX",
"Inst_TRMBON01.SYX",
"Inst_TRMPET01.SYX",
"Inst_TRMPET02.SYX",
"Inst_TRUMPET.SYX",
"Inst_TXGE28.syx",
"Inst_TXGE29.syx",
"Inst_Tuba.syx",
"Inst_Tuba1.syx",
"Inst_VARYFAV1.SYX",
"Inst_VIBRAP01.SYX",
"Inst_VIBRAP02.SYX",
"Inst_VIOLIN01.SYX",
"Inst_VIOLIN02.SYX",
"Inst_VOCFEM1.SYX",
"Inst_VOCFEM2.SYX",
"Inst_VOCFEM3.SYX",
"Inst_VOCMALE1.SYX",
"Inst_VOCMALE2.SYX",
"Inst_VOCMALE3.SYX",
"Inst_VOCMISC.SYX",
"Inst_VOCODER1.SYX",
"Inst_VOCODER2.SYX",
"Inst_VOC_M_F.SYX",
"Inst_VOICE01.SYX",
"Inst_VOICE02.SYX",
"Inst_VOICE03.SYX",
"Inst_VOICE04.SYX",
"Inst_VOICE05.SYX",
"Inst_VOICE06.SYX",
"Inst_VOICE07.SYX",
"Inst_WARM35.SYX",
"Inst_WARM3A.SYX",
"Inst_WARM3B.SYX",
"Inst_WEIRD1.SYX",
"Inst_WEIRD2.SYX",
"Inst_WEIRD3.SYX",
"Inst_WHEATLEY.SYX",
"Inst_WHITE.SYX",
"Inst_WIND--01.SYX",
"Inst_WIND--02.SYX",
"Inst_WIND--03.SYX",
"Inst_WIND--04.SYX",
"Inst_WIND--05.SYX",
"Inst_WODWIND1.SYX",
"Inst_WOODWI01.SYX",
"Inst_WOODWI02.SYX",
"Inst_WOODWI03.SYX",
"Inst_WOODWI04.SYX",
"Inst_WOODWI05.SYX",
"Inst_WOODWIND.SYX",
"Inst_WURLIT11.SYX",
"Inst_WWIND1.SYX",
"Inst_WWIND2.SYX",
"Inst_Wind.SYX",
"Inst_bass6.syx",
"Inst_bass_04.syx",
"Inst_bass_07.syx",
"Inst_bass_13.syx",
"Inst_bass_14.syx",
"Inst_bell3.syx",
"Inst_brass8a.syx",
"Inst_brass_01.syx",
"Inst_brass_14.syx",
"Inst_cello_01.syx",
"Inst_cello_02.syx",
"Inst_choir4.syx",
"Inst_church.syx",
"Inst_clarinet.syx",
"Inst_clav_01.syx",
"Inst_clav_02.syx",
"Inst_clav_03.syx",
"Inst_clav_04.syx",
"Inst_clav_05.syx",
"Inst_clav_06.syx",
"Inst_ePian-25.syx",
"Inst_ePian-27.syx",
"Inst_ePian-28.syx",
"Inst_effects1a.syx",
"Inst_gtrs_a-d.syx",
"Inst_gtrs_n-r.syx",
"Inst_harmonica.syx",
"Inst_harp_1.syx",
"Inst_harp_2.syx",
"Inst_harpsi_1.syx",
"Inst_harpsi_2.syx",
"Inst_koto2.syx",
"Inst_libra_2.SYX",
"Inst_organ5.syx",
"Inst_organ_01.syx",
"Inst_organ_02.syx",
"Inst_organ_03.syx",
"Inst_organ_04.syx",
"Inst_organ_05.syx",
"Inst_organ_06.syx",
"Inst_organ_07.syx",
"Inst_organ_08.syx",
"Inst_organ_b3.syx",
"Inst_organham.syx",
"Inst_orgpipe1.syx",
"Inst_orgpipe2.syx",
"Inst_perc04.syx",
"Inst_perc07.syx",
"Inst_perc08.syx",
"Inst_perc11.syx",
"Inst_rhodes3.syx",
"Inst_strnga-a.syx",
"Inst_strnga-b.syx",
"Inst_strngac2.syx",
"Inst_strngac4.syx",
"Inst_strngb-d.syx",
"Inst_strngd-h.syx",
"Inst_strngh-k.syx",
"Inst_strngk-o.syx",
"Inst_strngs01.syx",
"Inst_strngs02.syx",
"Inst_strngs03.syx",
"Inst_strngs04.syx",
"Inst_strngs05.syx",
"Inst_strngs06.syx",
"Inst_strngs07.syx",
"Inst_strngs08.syx",
"Inst_strngs09.syx",
"Inst_strngs10.syx",
"Inst_strngs12.syx",
"Inst_strngs13.syx",
"Inst_strngs14.syx",
"Inst_strngs15.syx",
"Inst_strngs16.syx",
"Inst_strngs17.syx",
"Inst_strngs18.syx",
"Inst_strngs19.syx",
"Inst_strngs20.syx",
"Inst_strngsol2.syx",
"Inst_strngsol3.syx",
"Inst_strngsyn4.syx",
"Inst_strngsyn5.syx",
"Inst_syndec2.syx",
"Inst_syndec7.syx",
"Inst_syndec8.syx",
"Inst_syndec9.syx",
"Inst_synsus01.syx",
"Inst_synsus03.syx",
"Inst_synsus07.syx",
"Inst_synsus08.syx",
"Inst_synsus09.syx",
"Inst_synsus18.syx",
"Inst_synsus19.syx",
"Inst_synth_14.syx",
"Inst_synth_16.syx",
"Inst_various.syx",
"Inst_violin_1.syx",
"Inst_voices_1.syx",
"Inst_voices_2.syx",
"Inst_voices_3.syx",
"Inst_voices_5.syx",
"Inst_voices_7.syx",
"Inst_voices_8.syx",
"Inst_voices_9.syx",
"Inst_wodwind2.syx",
"Inst_wodwind3.syx",
"Inst_wodwind4.syx",
"Inst_wodwind5.syx",
"Inst_wodwind6.syx",
"Inst_wurlizer.syx",
"JackDeck_OboeBassoon.syx",
"JackDeck_RamBank.syx",
"JackDeck_RamCartridge.syx",
"JackDeck_aegix.syx",
"JackDeck_analog_1.syx",
"JackDeck_analog_2.syx",
"JackDeck_analog_3.syx",
"JackDeck_bass_01.syx",
"JackDeck_bass_02.syx",
"JackDeck_bass_03.syx",
"JackDeck_bass_04.syx",
"JackDeck_bass_05.syx",
"JackDeck_bass_06.syx",
"JackDeck_bass_07.syx",
"JackDeck_bass_08.syx",
"JackDeck_bass_09.syx",
"JackDeck_bass_10.syx",
"JackDeck_bass_11.syx",
"JackDeck_bass_12.syx",
"JackDeck_bass_13.syx",
"JackDeck_bass_14.syx",
"JackDeck_bass_15.syx",
"JackDeck_bells_01.syx",
"JackDeck_bells_02.syx",
"JackDeck_bells_03.syx",
"JackDeck_boruff.syx",
"JackDeck_brass_01.syx",
"JackDeck_brass_02.syx",
"JackDeck_brass_03.syx",
"JackDeck_brass_04.syx",
"JackDeck_brass_05.syx",
"JackDeck_brass_06.syx",
"JackDeck_brass_07.syx",
"JackDeck_brass_08.syx",
"JackDeck_brass_09.syx",
"JackDeck_brass_10.syx",
"JackDeck_brass_11.syx",
"JackDeck_brass_12.syx",
"JackDeck_brass_13.syx",
"JackDeck_brass_14.syx",
"JackDeck_brass_15.syx",
"JackDeck_brass_16.syx",
"JackDeck_brass_17.syx",
"JackDeck_brass_18.syx",
"JackDeck_c-lab_1.syx",
"JackDeck_cello_01.syx",
"JackDeck_cello_02.syx",
"JackDeck_church.syx",
"JackDeck_ciani.syx",
"JackDeck_clarinet.syx",
"JackDeck_clav_01.syx",
"JackDeck_clav_02.syx",
"JackDeck_clav_03.syx",
"JackDeck_clav_04.syx",
"JackDeck_clav_05.syx",
"JackDeck_clav_06.syx",
"JackDeck_compuerr.syx",
"JackDeck_czeiszpe.syx",
"JackDeck_dave1.syx",
"JackDeck_deckard.syx",
"JackDeck_divers.syx",
"JackDeck_drt1.syx",
"JackDeck_drt2.syx",
"JackDeck_dx9.syx",
"JackDeck_effects1.syx",
"JackDeck_effects2.syx",
"JackDeck_effects3.syx",
"JackDeck_effects4.syx",
"JackDeck_effects5.syx",
"JackDeck_effects6.syx",
"JackDeck_effects7.syx",
"JackDeck_effects8.syx",
"JackDeck_fatstuff.syx",
"JackDeck_flute.syx",
"JackDeck_gtrs_01.syx",
"JackDeck_gtrs_a-d.syx",
"JackDeck_gtrs_d.syx",
"JackDeck_gtrs_el.syx",
"JackDeck_gtrs_g-j.syx",
"JackDeck_gtrs_j-k.syx",
"JackDeck_gtrs_l-n.syx",
"JackDeck_gtrs_n-r.syx",
"JackDeck_gtrs_s-v.syx",
"JackDeck_gtrsonus.syx",
"JackDeck_harmonic.syx",
"JackDeck_harp_1.syx",
"JackDeck_harp_2.syx",
"JackDeck_harpsi_1.syx",
"JackDeck_harpsi_2.syx",
"JackDeck_keybds01.syx",
"JackDeck_king.syx",
"JackDeck_koto.syx",
"JackDeck_laser.syx",
"JackDeck_misc_01.syx",
"JackDeck_misc_02.syx",
"JackDeck_misc_03.syx",
"JackDeck_misc_04.syx",
"JackDeck_misc_05.syx",
"JackDeck_misc_06.syx",
"JackDeck_misc_07.syx",
"JackDeck_misc_08.syx",
"JackDeck_misc_09.syx",
"JackDeck_misc_10.syx",
"JackDeck_misc_11.syx",
"JackDeck_misc_12.syx",
"JackDeck_misc_13.syx",
"JackDeck_misc_14.syx",
"JackDeck_misc_15.syx",
"JackDeck_misc_16.syx",
"JackDeck_misc_17.syx",
"JackDeck_misc_18.syx",
"JackDeck_misc_19.syx",
"JackDeck_misc_20.syx",
"JackDeck_misc_21.syx",
"JackDeck_misc_22.syx",
"JackDeck_misc_23.syx",
"JackDeck_misc_24.syx",
"JackDeck_misc_25.syx",
"JackDeck_misc_26.syx",
"JackDeck_misc_27.syx",
"JackDeck_misc_28.syx",
"JackDeck_misc_29.syx",
"JackDeck_misc_30.syx",
"JackDeck_misc_31.syx",
"JackDeck_misc_32.syx",
"JackDeck_misc_33.syx",
"JackDeck_misc_34.syx",
"JackDeck_monteleo.syx",
"JackDeck_moog.syx",
"JackDeck_mortega.syx",
"JackDeck_orch_1.syx",
"JackDeck_orchestr.syx",
"JackDeck_organ_01.syx",
"JackDeck_organ_02.syx",
"JackDeck_organ_03.syx",
"JackDeck_organ_04.syx",
"JackDeck_organ_05.syx",
"JackDeck_organ_06.syx",
"JackDeck_organ_07.syx",
"JackDeck_organ_08.syx",
"JackDeck_organ_b3.syx",
"JackDeck_organham.syx",
"JackDeck_orgpipe1.syx",
"JackDeck_orgpipe2.syx",
"JackDeck_pearson.syx",
"JackDeck_pedanna.syx",
"JackDeck_percus01.syx",
"JackDeck_percus02.syx",
"JackDeck_percus03.syx",
"JackDeck_percus04.syx",
"JackDeck_percus05.syx",
"JackDeck_percus06.syx",
"JackDeck_percus07.syx",
"JackDeck_percus08.syx",
"JackDeck_percus09.syx",
"JackDeck_percus10.syx",
"JackDeck_percvibe.syx",
"JackDeck_personus.syx",
"JackDeck_piano_01.syx",
"JackDeck_piano_02.syx",
"JackDeck_piano_03.syx",
"JackDeck_piano_04.syx",
"JackDeck_piano_05.syx",
"JackDeck_piano_06.syx",
"JackDeck_piano_07.syx",
"JackDeck_piano_08.syx",
"JackDeck_piano_09.syx",
"JackDeck_piano_10.syx",
"JackDeck_piano_11.syx",
"JackDeck_piano_12.syx",
"JackDeck_piano_13.syx",
"JackDeck_piano_a1.syx",
"JackDeck_piano_e1.syx",
"JackDeck_piano_e2.syx",
"JackDeck_piano_e3.syx",
"JackDeck_piano_e4.syx",
"JackDeck_piano_e5.syx",
"JackDeck_pr01.syx",
"JackDeck_pro2.syx",
"JackDeck_ramNbank.syx",
"JackDeck_rambank1.syx",
"JackDeck_ramcart.syx",
"JackDeck_ramcartp.syx",
"JackDeck_rhodes1.syx",
"JackDeck_rhodes2.syx",
"JackDeck_rlegnini.syx",
"JackDeck_rom3a.syx",
"JackDeck_rom3b.syx",
"JackDeck_rom4a.syx",
"JackDeck_rom4b.syx",
"JackDeck_sax_01.syx",
"JackDeck_sax_02.syx",
"JackDeck_sitar.syx",
"JackDeck_spangler.syx",
"JackDeck_splits.syx",
"JackDeck_strnga-a.syx",
"JackDeck_strnga-b.syx",
"JackDeck_strngb-d.syx",
"JackDeck_strngd-h.syx",
"JackDeck_strngh-k.syx",
"JackDeck_strngk-o.syx",
"JackDeck_strngs01.syx",
"JackDeck_strngs02.syx",
"JackDeck_strngs03.syx",
"JackDeck_strngs04.syx",
"JackDeck_strngs05.syx",
"JackDeck_strngs06.syx",
"JackDeck_strngs07.syx",
"JackDeck_strngs08.syx",
"JackDeck_strngs09.syx",
"JackDeck_strngs10.syx",
"JackDeck_strngs12.syx",
"JackDeck_strngs13.syx",
"JackDeck_strngs14.syx",
"JackDeck_strngs15.syx",
"JackDeck_strngs16.syx",
"JackDeck_strngs17.syx",
"JackDeck_strngs18.syx",
"JackDeck_strngs19.syx",
"JackDeck_strngs20.syx",
"JackDeck_sustain1.syx",
"JackDeck_synth_01.syx",
"JackDeck_synth_02.syx",
"JackDeck_synth_03.syx",
"JackDeck_synth_04.syx",
"JackDeck_synth_05.syx",
"JackDeck_synth_06.syx",
"JackDeck_synth_07.syx",
"JackDeck_synth_08.syx",
"JackDeck_synth_09.syx",
"JackDeck_synth_10.syx",
"JackDeck_synth_11.syx",
"JackDeck_synth_12.syx",
"JackDeck_synth_13.syx",
"JackDeck_synth_14.syx",
"JackDeck_synth_15.syx",
"JackDeck_synth_16.syx",
"JackDeck_synth_17.syx",
"JackDeck_synth_18.syx",
"JackDeck_synth_19.syx",
"JackDeck_synth_20.syx",
"JackDeck_synth_21.syx",
"JackDeck_synth_22.syx",
"JackDeck_textures.syx",
"JackDeck_trumpet.syx",
"JackDeck_violin_1.syx",
"JackDeck_voices_1.syx",
"JackDeck_voices_2.syx",
"JackDeck_voices_3.syx",
"JackDeck_voices_5.syx",
"JackDeck_voices_6.syx",
"JackDeck_voices_7.syx",
"JackDeck_voices_8.syx",
"JackDeck_voices_9.syx",
"JackDeck_wheatley.syx",
"JackDeck_white.syx",
"JackDeck_wodwind1.syx",
"JackDeck_wodwind2.syx",
"JackDeck_wodwind3.syx",
"JackDeck_wodwind4.syx",
"JackDeck_wodwind5.syx",
"JackDeck_wodwind6.syx",
"JackDeck_wurlizer.syx",
"KBMag_syx",
"KB_MAG1.syx",
"KB_MAG2.syx",
"KB_MAG3.syx",
"LiveMusic_ACCPIANO.SYX",
"LiveMusic_ACORDIAN.SYX",
"LiveMusic_ANALOG-1.SYX",
"LiveMusic_ANALOG-2.SYX",
"LiveMusic_ANALOG-3.SYX",
"LiveMusic_ANALOG-4.SYX",
"LiveMusic_ANALOG1A.SYX",
"LiveMusic_ANALOG1B.SYX",
"LiveMusic_ANALOG2A.SYX",
"LiveMusic_ANALOG2B.SYX",
"LiveMusic_BASS1.SYX",
"LiveMusic_BASS2.SYX",
"LiveMusic_BASSMAN.SYX",
"LiveMusic_BELLS2.SYX",
"LiveMusic_BRASS.SYX",
"LiveMusic_BRASS1.SYX",
"LiveMusic_BRASS2.SYX",
"LiveMusic_BRDRANGE.SYX",
"LiveMusic_CALLHANK.SYX",
"LiveMusic_CARLOS.SYX",
"LiveMusic_CLASSIC1.SYX",
"LiveMusic_CLAVOR2.SYX",
"LiveMusic_CLAVS1.SYX",
"LiveMusic_COUNTRY.SYX",
"LiveMusic_COWBELL.SYX",
"LiveMusic_DIGITAL1.SYX",
"LiveMusic_DIGITAL2.SYX",
"LiveMusic_DIGITAL3.SYX",
"LiveMusic_DIGITAL4.SYX",
"LiveMusic_DIGITAL5.SYX",
"LiveMusic_DRUMS.SYX",
"LiveMusic_EFFECTS1.SYX",
"LiveMusic_EFFECTS2.SYX",
"LiveMusic_ENSEMBLE.SYX",
"LiveMusic_EPIANO1.SYX",
"LiveMusic_EPIANO2.SYX",
"LiveMusic_FLNGRODE.SYX",
"LiveMusic_GLASS.SYX",
"LiveMusic_GOODGRP.SYX",
"LiveMusic_GRAB-BAG.SYX",
"LiveMusic_GUITARS.SYX",
"LiveMusic_HIMNVC.SYX",
"LiveMusic_I-ROBOT.SYX",
"LiveMusic_IVRYCITY.SYX",
"LiveMusic_KOTO.SYX",
"LiveMusic_LONDON.SYX",
"LiveMusic_MALLETS1.SYX",
"LiveMusic_MARS.SYX",
"LiveMusic_MONEY.SYX",
"LiveMusic_MONEY2.SYX",
"LiveMusic_MORSPLTZ.SYX",
"LiveMusic_MORSYNTH.SYX",
"LiveMusic_MULTS1.SYX",
"LiveMusic_MUSICBOX.SYX",
"LiveMusic_MUSICTRN.SYX",
"LiveMusic_NEWTEETH.SYX",
"LiveMusic_ORGANS.SYX",
"LiveMusic_ORGANS1.SYX",
"LiveMusic_PERCUSS1.SYX",
"LiveMusic_PERCUSS2.SYX",
"LiveMusic_PIKAHORN.SYX",
"LiveMusic_PIPES.SYX",
"LiveMusic_PKPOKBLO.SYX",
"LiveMusic_PLUCKED1.SYX",
"LiveMusic_PLUCKED2.SYX",
"LiveMusic_PROHNGN.SYX",
"LiveMusic_PROPHET.SYX",
"LiveMusic_ROM3BV.SYX",
"LiveMusic_ROSNBOW.SYX",
"LiveMusic_RYTHSECA.SYX",
"LiveMusic_RYTHSECB.SYX",
"LiveMusic_SCORPIO.SYX",
"LiveMusic_SJSU-G.SYX",
"LiveMusic_SNDEFXA.SYX",
"LiveMusic_SNDEFXB.SYX",
"LiveMusic_SOMSPLTZ.SYX",
"LiveMusic_SPLITZ.SYX",
"LiveMusic_SPRSPLTA.SYX",
"LiveMusic_SPRSPLTB.SYX",
"LiveMusic_STEVE.SYX",
"LiveMusic_STRINGS.SYX",
"LiveMusic_STRINGS1.SYX",
"LiveMusic_STRINGS2.SYX",
"LiveMusic_STRNGEFX.SYX",
"LiveMusic_SYN-CITY.SYX",
"LiveMusic_TOP40A.SYX",
"LiveMusic_TOP40B.SYX",
"LiveMusic_TRAMP.SYX",
"LiveMusic_TX1.SYX",
"LiveMusic_TX10.SYX",
"LiveMusic_TX11.SYX",
"LiveMusic_TX12.SYX",
"LiveMusic_TX14.SYX",
"LiveMusic_TX15.SYX",
"LiveMusic_TX16.SYX",
"LiveMusic_TX17.SYX",
"LiveMusic_TX18.SYX",
"LiveMusic_TX19.SYX",
"LiveMusic_TX2.SYX",
"LiveMusic_TX20.SYX",
"LiveMusic_TX21.SYX",
"LiveMusic_TX22.SYX",
"LiveMusic_TX23.SYX",
"LiveMusic_TX24.SYX",
"LiveMusic_TX25.SYX",
"LiveMusic_TX26.SYX",
"LiveMusic_TX27.SYX",
"LiveMusic_TX28.SYX",
"LiveMusic_TX29.SYX",
"LiveMusic_TX3.SYX",
"LiveMusic_TX30.SYX",
"LiveMusic_TX31.SYX",
"LiveMusic_TX32.SYX",
"LiveMusic_TX33.SYX",
"LiveMusic_TX34.SYX",
"LiveMusic_TX35.SYX",
"LiveMusic_TX36.SYX",
"LiveMusic_TX37.SYX",
"LiveMusic_TX38.SYX",
"LiveMusic_TX39.SYX",
"LiveMusic_TX4.SYX",
"LiveMusic_TX40.SYX",
"LiveMusic_TX41.SYX",
"LiveMusic_TX42.SYX",
"LiveMusic_TX43.SYX",
"LiveMusic_TX44.SYX",
"LiveMusic_TX45.SYX",
"LiveMusic_TX46.SYX",
"LiveMusic_TX47.SYX",
"LiveMusic_TX48.SYX",
"LiveMusic_TX49.SYX",
"LiveMusic_TX5.SYX",
"LiveMusic_TX50.SYX",
"LiveMusic_TX51.SYX",
"LiveMusic_TX53.SYX",
"LiveMusic_TX54.SYX",
"LiveMusic_TX55.SYX",
"LiveMusic_TX56.SYX",
"LiveMusic_TX57.SYX",
"LiveMusic_TX58.SYX",
"LiveMusic_TX59.SYX",
"LiveMusic_TX6.SYX",
"LiveMusic_TX60.SYX",
"LiveMusic_TX61.SYX",
"LiveMusic_TX62.SYX",
"LiveMusic_TX63.SYX",
"LiveMusic_TX64.SYX",
"LiveMusic_TX65.SYX",
"LiveMusic_TX66.SYX",
"LiveMusic_TX68.SYX",
"LiveMusic_TX69.SYX",
"LiveMusic_TX7.SYX",
"LiveMusic_TX70.SYX",
"LiveMusic_TX71.SYX",
"LiveMusic_TX72.SYX",
"LiveMusic_TX73.SYX",
"LiveMusic_TX74.SYX",
"LiveMusic_TX76.SYX",
"LiveMusic_TX77.SYX",
"LiveMusic_TX79.SYX",
"LiveMusic_TX8.SYX",
"LiveMusic_TX80.SYX",
"LiveMusic_TX81.SYX",
"LiveMusic_TX82.SYX",
"LiveMusic_TX83.SYX",
"LiveMusic_TX85.SYX",
"LiveMusic_TX86.SYX",
"LiveMusic_TX87.SYX",
"LiveMusic_TX88.SYX",
"LiveMusic_TX89.SYX",
"LiveMusic_TX9.SYX",
"LiveMusic_TX90.SYX",
"LiveMusic_TX91.SYX",
"LiveMusic_TX92.SYX",
"LiveMusic_TX93.SYX",
"LiveMusic_TX94.SYX",
"LiveMusic_TX95.SYX",
"LiveMusic_TX96.SYX",
"LiveMusic_TX97.SYX",
"LiveMusic_VARETY.SYX",
"LiveMusic_VOICES1.SYX",
"LiveMusic_WDWINDS1.SYX",
"LiveMusic_WEDING1.SYX",
"LiveMusic_WEDING2.SYX",
"LiveMusic_XYLOS-V.SYX",
"MSX_2.syx",
"Metra_Percussion1.SYX",
"Metra_Percussion2.SYX",
"Metra_Samples 1.SYX",
"Metra_Samples2.SYX",
"RAY-01.SYX",
"RAY-02.SYX",
"RAY-03.SYX",
"RAY-04.SYX",
"RAY-06.SYX",
"RAY-07.SYX",
"RAY-08.SYX",
"RAY-09.SYX",
"RAY-10.SYX",
"RAY-11.SYX",
"RAY-12.SYX",
"RAY-13.SYX",
"RAY-14.SYX",
"RAY-16.SYX",
"RAY-17.SYX",
"RAY-18.SYX",
"RAY-19.SYX",
"RAY-20.SYX",
"RAY-21.SYX",
"SOLANGE0.SYX",
"SOLANGE1.SYX",
"SOLANGE2.SYX",
"SOLANGE3.SYX",
"SOLANGE4.SYX",
"SOLANGE5.SYX",
"SOLANGE6.SYX",
"SOLANGE7.SYX",
"SOLANGE8.SYX",
"SOLANGE9.SYX",
"SONUS01.SYX",
"SONUS02.SYX",
"SONUS03.SYX",
"SONUS04.SYX",
"SONUS05.SYX",
"SONUS06.SYX",
"SONUS07.SYX",
"SONUS08.SYX",
"SONUS09.SYX",
"SONUS10.SYX",
"SndVert_04.SYX",
"SndVert_10.SYX",
"SndVert_11.SYX",
"SuperMax_1.SYX",
"SuperMax_2.SYX",
"SyntechColl_0.SYX",
"SyntechColl_1.SYX",
"SyntechColl_2.SYX",
"SyntechColl_3.SYX",
"SyntechColl_4.SYX",
"SyntechColl_5.SYX",
"SyntechColl_6.SYX",
"SyntechColl_7.SYX",
"SyntechColl_8.SYX",
"SyntechColl_9.SYX",
"Tobys1.syx",
"Tobys2.syx",
"YamBB_rom1a.syx",
"YamBB_rom1b.syx",
"YamBB_rom2a.syx",
"YamBB_rom2b.syx",
"YamBB_rom3a.syx",
"YamBB_rom3b.syx",
"YamBB_rom4a.syx",
"YamBB_rom4b.syx",
"YamBB_vrc101a.syx",
"YamBB_vrc101b.syx",
"YamBB_vrc102a.syx",
"YamBB_vrc102b.syx",
"YamBB_vrc103a.syx",
"YamBB_vrc103b.syx",
"YamBB_vrc104a.syx",
"YamBB_vrc104b.syx",
"YamBB_vrc105a.syx",
"YamBB_vrc105b.syx",
"YamBB_vrc106a.syx",
"YamBB_vrc106b.syx",
"YamBB_vrc107a.syx",
"YamBB_vrc107b.syx",
"YamBB_vrc108a.syx",
"YamBB_vrc108b.syx",
"YamBB_vrc109a.syx",
"YamBB_vrc109b.syx",
"YamBB_vrc110a.syx",
"YamBB_vrc110b.syx",
"YamBB_vrc111a.syx",
"YamBB_vrc111b.syx",
"YamBB_vrc112a.syx",
"YamBB_vrc112b.syx",
"allsyx",
"allsyx_BUCK-1.SYX",
"allsyx_BUCK-2.SYX",
"allsyx_DRM2.SYX",
"allsyx_DRM2A.SYX",
"allsyx_DRMOCT.SYX",
"allsyx_EFFECT-1.SYX",
"allsyx_EFFECT-2.SYX",
"allsyx_ESIPA.SYX",
"allsyx_GIG-1.SYX",
"allsyx_GREGEEA.SYX",
"allsyx_GREGEEB.SYX",
"allsyx_GREGEEC.SYX",
"allsyx_GREGEED.SYX",
"allsyx_METAL.SYX",
"allsyx_MF.SYX",
"allsyx_POWERPLY.SYX",
"allsyx_RAY-1.SYX",
"allsyx_RAY-10.SYX",
"allsyx_RAY-11.SYX",
"allsyx_RAY-12.SYX",
"allsyx_RAY-13.SYX",
"allsyx_RAY-14.SYX",
"allsyx_RAY-15.SYX",
"allsyx_RAY-16.SYX",
"allsyx_RAY-17.SYX",
"allsyx_RAY-18.SYX",
"allsyx_RAY-19.SYX",
"allsyx_RAY-2.SYX",
"allsyx_RAY-20.SYX",
"allsyx_RAY-21.SYX",
"allsyx_RAY-3.SYX",
"allsyx_RAY-4.SYX",
"allsyx_RAY-5.SYX",
"allsyx_RAY-6.SYX",
"allsyx_RAY-7.SYX",
"allsyx_RAY-8.SYX",
"allsyx_RAY-9.SYX",
"allsyx_ROM-1.SYX",
"allsyx_ROM-2.SYX",
"allsyx_ROM-3.SYX",
"allsyx_ROM-4.SYX",
"allsyx_STEVE.SYX",
"dx7pat_ANALOG1.SYX",
"dx7pat_ANALOG3.SYX",
"dx7pat_ANALOG4.SYX",
"dx7pat_ANGELO.SYX",
"dx7pat_ATSU_4.SYX",
"dx7pat_ATSU_5.SYX",
"dx7pat_B1.SYX",
"dx7pat_B2.SYX",
"dx7pat_B3.SYX",
"dx7pat_B4.SYX",
"dx7pat_BANK0000.SYX",
"dx7pat_BANK0006.SYX",
"dx7pat_BANK0008.SYX",
"dx7pat_BANK0009.SYX",
"dx7pat_BANK0023.SYX",
"dx7pat_BANK0024.SYX",
"dx7pat_BANK0042.SYX",
"dx7pat_BANK0043.SYX",
"dx7pat_BANK0054.SYX",
"dx7pat_BANK0056.SYX",
"dx7pat_BANK01.SYX",
"dx7pat_BANK05.SYX",
"dx7pat_BANK08.SYX",
"dx7pat_BANK11.SYX",
"dx7pat_BANK14.SYX",
"dx7pat_BANK18.SYX",
"dx7pat_BASSEA.SYX",
"dx7pat_BASSICS.SYX",
"dx7pat_BBANK1.SYX",
"dx7pat_BBANK2.SYX",
"dx7pat_BELLS.SYX",
"dx7pat_BELLTEL.SYX",
"dx7pat_BLANKS.SYX",
"dx7pat_BRASS.SYX",
"dx7pat_BRASS2.SYX",
"dx7pat_BRASS3.SYX",
"dx7pat_BSTX.SYX",
"dx7pat_CHURCH.SYX",
"dx7pat_CLANG1.SYX",
"dx7pat_CLAUDE.SYX",
"dx7pat_CLAV1.SYX",
"dx7pat_CLAVS.SYX",
"dx7pat_COMBO.SYX",
"dx7pat_CONTEMP.SYX",
"dx7pat_COUNTRY.SYX",
"dx7pat_DAVE1.SYX",
"dx7pat_DG1.SYX",
"dx7pat_DG2.SYX",
"dx7pat_DJW001.SYX",
"dx7pat_DX5A1.SYX",
"dx7pat_DX5A2.SYX",
"dx7pat_DX5B1.SYX",
"dx7pat_DX5B2.SYX",
"dx7pat_DX7_0628.SYX",
"dx7pat_DXDXMI.SYX",
"dx7pat_DXMIK2.SYX",
"dx7pat_DXOC01.SYX",
"dx7pat_DXOC02.SYX",
"dx7pat_DXOC03.SYX",
"dx7pat_DXOC04.SYX",
"dx7pat_DXOC05.SYX",
"dx7pat_DXOC06.SYX",
"dx7pat_DXOC07.SYX",
"dx7pat_DXOC08.SYX",
"dx7pat_DXOC09.SYX",
"dx7pat_DXOC10.SYX",
"dx7pat_DXOC11.SYX",
"dx7pat_DXOC12.SYX",
"dx7pat_DXOC13.SYX",
"dx7pat_DXOC14.SYX",
"dx7pat_DXOC15.SYX",
"dx7pat_DXOC16.SYX",
"dx7pat_DXOC17.SYX",
"dx7pat_DXOC18.SYX",
"dx7pat_DXOC19.SYX",
"dx7pat_DXOC20.SYX",
"dx7pat_DXOC21.SYX",
"dx7pat_DXOC22.SYX",
"dx7pat_DXOC23.SYX",
"dx7pat_DXOC24.SYX",
"dx7pat_DXOC25.SYX",
"dx7pat_DXOC26.SYX",
"dx7pat_DXOC27.SYX",
"dx7pat_DXOC28.SYX",
"dx7pat_DXOC29.SYX",
"dx7pat_DXOC30.SYX",
"dx7pat_DXPLUK.SYX",
"dx7pat_EFFECTS1.SYX",
"dx7pat_EFX.SYX",
"dx7pat_ETHNIC.SYX",
"dx7pat_FORRICK.SYX",
"dx7pat_FRANK1.SYX",
"dx7pat_FRANKIE.SYX",
"dx7pat_GRAK.SYX",
"dx7pat_GUITAR1.SYX",
"dx7pat_GUITAR2.SYX",
"dx7pat_GUITARS.SYX",
"dx7pat_INT.SYX",
"dx7pat_ITALIAN2.SYX",
"dx7pat_ITALIAN3.SYX",
"dx7pat_JB001.SYX",
"dx7pat_JB002.SYX",
"dx7pat_JFD001.SYX",
"dx7pat_KEYBOARD.SYX",
"dx7pat_KEYS.SYX",
"dx7pat_KOTO.SYX",
"dx7pat_KQ_SAMPL.SYX",
"dx7pat_LATIN.SYX",
"dx7pat_LONNIE2.SYX",
"dx7pat_MAGAZINE.SYX",
"dx7pat_MALLETS1.SYX",
"dx7pat_MALLETS2.SYX",
"dx7pat_MARK.SYX",
"dx7pat_MARTY1.SYX",
"dx7pat_MARTY2.SYX",
"dx7pat_MASSEY.SYX",
"dx7pat_MIKE1.SYX",
"dx7pat_MIKE2.SYX",
"dx7pat_MORE_KEY.SYX",
"dx7pat_NEWSERI.SYX",
"dx7pat_NEWSND.SYX",
"dx7pat_ORCHESTR.SYX",
"dx7pat_ORGAN1.SYX",
"dx7pat_ORGAN2.SYX",
"dx7pat_ORGAN3.SYX",
"dx7pat_ORGANS.SYX",
"dx7pat_ORG_CLAV.SYX",
"dx7pat_ORTEGA1.SYX",
"dx7pat_ORTEGA10.SYX",
"dx7pat_ORTEGA11.SYX",
"dx7pat_ORTEGA12.SYX",
"dx7pat_ORTEGA13.SYX",
"dx7pat_ORTEGA14.SYX",
"dx7pat_ORTEGA15.SYX",
"dx7pat_ORTEGA16.SYX",
"dx7pat_ORTEGA17.SYX",
"dx7pat_ORTEGA18.SYX",
"dx7pat_ORTEGA19.SYX",
"dx7pat_ORTEGA2.SYX",
"dx7pat_ORTEGA20.SYX",
"dx7pat_ORTEGA3.SYX",
"dx7pat_ORTEGA4.SYX",
"dx7pat_ORTEGA5.SYX",
"dx7pat_ORTEGA6.SYX",
"dx7pat_ORTEGA7.SYX",
"dx7pat_ORTEGA8.SYX",
"dx7pat_ORTEGA9.SYX",
"dx7pat_PARTIAL.SYX",
"dx7pat_PERC1.SYX",
"dx7pat_PERC2.SYX",
"dx7pat_PERCUSS.SYX",
"dx7pat_PERCUSSI.SYX",
"dx7pat_PERC_A.SYX",
"dx7pat_PERC_B.SYX",
"dx7pat_PIANO32.SYX",
"dx7pat_PIANODX7.SYX",
"dx7pat_PLUCKED.SYX",
"dx7pat_PR01.SYX",
"dx7pat_PR02.SYX",
"dx7pat_PR03.SYX",
"dx7pat_RHODES1.SYX",
"dx7pat_RHODES2.SYX",
"dx7pat_RM0001.SYX",
"dx7pat_ROAD1.SYX",
"dx7pat_ROAD2.SYX",
"dx7pat_ROM1A.SYX",
"dx7pat_ROM1B.SYX",
"dx7pat_ROM2A.SYX",
"dx7pat_ROM2B.SYX",
"dx7pat_ROM3A.SYX",
"dx7pat_ROM3B.SYX",
"dx7pat_ROM4A.SYX",
"dx7pat_ROM4B.SYX",
"dx7pat_SJSU-E.SYX",
"dx7pat_SJSU-F.SYX",
"dx7pat_SJSU-G.SYX",
"dx7pat_SOLANGE2.SYX",
"dx7pat_SOLANGE3.SYX",
"dx7pat_SOLANGE4.SYX",
"dx7pat_SOLANGE5.SYX",
"dx7pat_SOLANGE6.SYX",
"dx7pat_SOLANGE7.SYX",
"dx7pat_SOLANGE8.SYX",
"dx7pat_SONUS1.SYX",
"dx7pat_SPLITS.SYX",
"dx7pat_SPLITSBN.SYX",
"dx7pat_STARMA.SYX",
"dx7pat_STEINBER.SYX",
"dx7pat_STEPH1.SYX",
"dx7pat_STEPH2.SYX",
"dx7pat_STEPH3.SYX",
"dx7pat_STEPH4.SYX",
"dx7pat_STEVE1.SYX",
"dx7pat_STRING1.SYX",
"dx7pat_STRING2.SYX",
"dx7pat_STRINGB.SYX",
"dx7pat_STRINGS.SYX",
"dx7pat_SUPERDX.SYX",
"dx7pat_SYNPLUS.SYX",
"dx7pat_SYNTHS32.SYX",
"dx7pat_SYNTHSBN.SYX",
"dx7pat_SYN_PLUS.SYX",
"dx7pat_TFI1.SYX",
"dx7pat_TFI2.SYX",
"dx7pat_TFI3.SYX",
"dx7pat_TFI4.SYX",
"dx7pat_TFI5.SYX",
"dx7pat_TFI6.SYX",
"dx7pat_TFI7.SYX",
"dx7pat_TFI8.SYX",
"dx7pat_TFRACK01.SYX",
"dx7pat_TFRACK02.SYX",
"dx7pat_THEATRE.SYX",
"dx7pat_THINGS.SYX",
"dx7pat_TX7A.SYX",
"dx7pat_WEIRD1.SYX",
"dx7pat_WEIRD2.SYX",
"dx7pat_WEIRD3.SYX",
"dx7pat_WOODWIND.SYX",
"dx7pat_WWIND1.SYX",
"dx7pat_WWIND2.SYX",
"dx7pat_WWIND3.SYX",
"dx7pat_WWIND4.SYX",
"dx7pat_WYATT.SYX",
"dx7pat_XYLOS.SYX",
"dx7pat_YAM-26.SYX",
"dx7pat_YAMAHA.SYX",
"dx7pat_ZONE3.SYX"];
//»

//let DEFAULT_BANK = "ANALOG-1.syx";
//let DEFAULT_BANK = "ShofukuPt1_KV01A.syx";

//let DEFAULT_BANK = "Powerply";
//let DEFAULT_PATCH = 19;//<-- Patch "Elmo Bell" on the lower keys!!!
//let DEFAULT_PATCH = 26;// "SloPwSwp.2" Just hold it down for that "eerie" feeling

//let DEFAULT_BANK = "Ray-1";
// 13 == BENDRASPN !!!
// 20 == FUNK BAS1 -> Standard 80's movie deal on the lower keys

let CUR_BANK;
export const app = function (arg) {

const {Core, Main, NS}=arg;
const{log,cwarn,cerr,api:capi, globals, Desk}=Core;
const{fs,util}=globals;
const{make,mkdv,mk,mksp}=util;

if (!globals.audio) Core.api.mkAudio();

const {mixer, ctx}=globals.audio;

let dx7;
let midikeys, user_settings;
let LIB;

class WAMController extends AudioWorkletNode{//«
  constructor(context,processorName,options){super(context,processorName,options);}
  setParam(key,value){this.port.postMessage({type:"param",key:key,value:value});  }
  setPatch(patch){this.port.postMessage({type:"patch",data:patch});  }
  setSysex(sysex){this.port.postMessage({type:"sysex",data:sysex});  }
  onMidi(msg) {
if (msg[0]===144) {
//	log(msg[1]);
}
    this.port.postMessage({ type:"midi", data:msg });
  } 
  
  set midiIn (port) {
    if (this._midiInPort) {
      this._midiInPort.close();
      this._midiInPort.onmidimessage = null;
    } 
    this._midiInPort = port;
    this._midiInPort.onmidimessage = function (msg) {
      this.port.postMessage({ type:"midi", data:msg.data });
    }.bind(this);
  } 
  
  sendMessage(verb, prop, data) {
    this.port.postMessage({ type:"msg", verb:verb, prop:prop, data:data });
  } 
  get gui () { return null; }
}//»

class DX7 extends WAMController{//«
  constructor (actx, options) {
    options = options || {};
    options.numberOfInputs  = 0;
    options.numberOfOutputs = 1;
    options.outputChannelCount = [1];

    super(actx, "DX7", options);
  }

	static importScripts () {
	//    var origin = location.origin + "/";
		return new Promise(async (Y,N) => {
	//      await actx.audioWorklet.addModule(origin + "worklet-module.js");
			await ctx.audioWorklet.addModule("/root/code/mods/av/synth/dx7/worklet-module.js");
			Y();
		})
	}
}//»

// webDX7 (WAM)//«
// bank and patch handling
// Jari Kleimola 2017 (jari@webaudiomodules.org)



var DX7Library = function ()//«
{
  this.banks = banklist;
  this.patches = [];
  this.bank = [];
  var self = this;
  
  this.load = filename => {
    var url = "/root/code/mods/av/synth/dx7/presets/" + filename;
cwarn(BANKITER, filename);
    return new Promise( (resolve,reject) => {
      fetch(url).then(resp => {
      resp.arrayBuffer().then(data => {
        // -- packed bank with sysex frame (32 patches)
//        if (data.byteLength != 4104) reject();
        self.patches = [];
        self.bank = [];
        data = new Uint8Array(data);
        data = data.subarray(6,4102);
        for (var i=0; i<32; i++) {
          var offset = i*128;
          var voice  = data.subarray(offset,offset+128);
          var name   = extractName(voice);
          self.patches.push(name);
          self.bank.push(voice);
//log(i, name);
        }
        resolve(self.bank);
      }) }) });
  }
  
  function extractName (data,offset) {
    var offset = offset || 118;	// 118 for packed, 145 for unpacked
    var name  = "";
    for (var n = 0; n < 10; n++) {
      var c = data[n + offset];
      switch (c) {
        case  92:  c = 'Y';  break;  // yen
        case 126:  c = '>';  break;  // >>
        case 127:  c = '<';  break;  // <<
        default: if (c < 32 || c > 127) c = 32; break;
      }
    name += String.fromCharCode(c);
    }
    return name;
  }
}//»

//»

function initGUI (lib) {//«

lib.banks.forEach( name => { 
//log(name);
//	banks.appendChild(new Option(name)); 
});
/*«
  var inited  = false;
  var banks   = document.getElementById("banks");
  var patches = document.getElementById("patches");
  lib.banks.forEach( name => { banks.appendChild(new Option(name)); });
  banks.onchange = function (e) {
    lib.load(e.target.value).then(bank => {
      patches.innerHTML = "";
      bank.forEach( name => { patches.appendChild(new Option(name)); });
      if (!inited) { inited = true; patches.selectedIndex = 10; }
      else patches.onchange({ target:patches });
    })
  }
  banks.onchange({ target:banks });
  patches.onchange = function (e) {
    var patch = lib.bank[e.target.selectedIndex];
    dx7.setPatch(patch);
  }
»*/
var velo = 80;
midikeys = new QwertyHancock({octaves: 6, startNote: 'C2', oct:4});
midikeys.keyDown = (note, name) => dx7.onMidi([0x90, note, velo]);
midikeys.keyUp   = (note, name) => dx7.onMidi([0x80, note, velo]);

}//»

//(function (window, undefined) {//«
//	var self = this;

	var notes = ["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"];
	var midimap = {
		90:0, 88:2, 67:4, 86:5, 66:7, 78:9, 77:11, 44:12, 46:14, 45:16,
		83:1, 68:3, 71:6, 72:8, 74:10, 76:13, 246:15,
		81:12, 87:14, 69:16, 82:17, 84:19, 89:21, 85:23, 73:24, 79:26, 80:28, 229:29,
		50:13, 51:15, 53:18, 54:20, 55:22, 57:25, 48:27
	};
	function getMidiKey(keyCode) { return midimap[keyCode]; }

    var version = '0.4.3',
        settings = {},
        mouse_is_down = false,
        keysDown = {},
        key_map = {
            65: 'Cl',
            87: 'C#l',
            83: 'Dl',
            69: 'D#l',
            68: 'El',
            70: 'Fl',
            84: 'F#l',
            71: 'Gl',
            89: 'G#l',
            90: 'G#l',
            72: 'Al',
            85: 'A#l',
            74: 'Bl',
            75: 'Cu',
            79: 'C#u',
            76: 'Du',
            80: 'D#u',
            59: 'Eu',
            186: 'Eu',
            222: 'Fu',
            221: 'F#u',
            220: 'Gu'
        },
        keyDownCallback,
        keyUpCallback;

    var init = function (us) {
        var container;
        user_settings = us || {};
        settings = {
            startNote:      user_settings.startNote || 'A3'
        };
		settings.oct = user_settings.oct;
		settings.startOctave = parseInt(settings.startNote.charAt(1), 10);
//		addListeners.call(this);
    };

    var getFrequencyOfNote = function (note) {
        var notes = ['A', 'A#', 'B', 'C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#'],
            key_number,
            octave;

        if (note.length === 3) {
            octave = note.charAt(2);
        } else {
            octave = note.charAt(1);
        }

        key_number = notes.indexOf(note.slice(0, -1));

        if (key_number < 3) {
            key_number = key_number + 12 + ((octave - 1) * 12) + 1;
        } else {
            key_number = key_number + ((octave - 1) * 12) + 1;
        }

        return 440 * Math.pow(2, (key_number - 49) / 12);
    };

	function name2note(name)
	{
		var oct = name.slice(-1);
		name = name.substring(0, name.length - 1);
		var i = notes.indexOf(name);
		var note = i + oct * 12;
		return note;
	}
 
	var keyboardDown = function (key, callback){
		if (key.keyIdentifier) {
			var unicode = key.keyIdentifier.substring(2);
			var i = parseInt(unicode,16); }
		else var i = key.keyCode;
		if (isNaN(i)) return;
		var midinote = getMidiKey(i);
		if (midinote == undefined) return;		 
		midinote += settings.oct*12;
		
		if (midinote in keysDown) return;		
		keysDown[midinote] = true;
		
		var keyname = notes[midinote % 12] + ((midinote/12)|0);
		callback(midinote, keyname);
	};
	 
	var keyboardUp = function (key, callback){
		if (key.keyIdentifier) {
			var unicode = key.keyIdentifier.substring(2);
			var i = parseInt(unicode,16); }
		else var i = key.keyCode;
		if (isNaN(i)) return;
		var midinote = getMidiKey(i);
		if (midinote == undefined) return;		 
		midinote += settings.oct*12;
		
		delete keysDown[midinote];

		var keyname = notes[midinote % 12] + ((midinote/12)|0);
		callback(midinote, keyname);
	};

    var QwertyHancock = function (settings) {
        this.version = version;

        this.keyDown = function () {
            // Placeholder function.
        };

        this.keyUp = function () {
            // Placeholder function.
        };

        init.call(this, settings);
    };


//»

const onkeydown = async (e, s)=>{
if (s=="UP_"){
if (PATCHITER == 0) PATCHITER = 31;
else PATCHITER--;
dx7.setPatch(CUR_BANK[PATCHITER]);
log(PATCHITER, LIB.patches[PATCHITER]);
}
else if (s=="DOWN_"){
if (PATCHITER==31) PATCHITER = 0;
else PATCHITER++;
dx7.setPatch(CUR_BANK[PATCHITER]);
log(PATCHITER, LIB.patches[PATCHITER]);
//cwarn(PATCHITER);
}
else if (s=="q_"){
	if (BANKITER == 0) BANKITER = ALL_BANKS.length - 1;
	else BANKITER--;
	CUR_BANK = await getbank();
//cwarn(ALL_BANKS[BANKITER]);
	PATCHITER = 0;
	dx7.setPatch(CUR_BANK[PATCHITER]);
log(PATCHITER, LIB.patches[PATCHITER]);
}
else if (s=="w_"){
	if (BANKITER == ALL_BANKS.length - 1) BANKITER = 0;
	else BANKITER++;
	CUR_BANK = await getbank();
//cwarn(ALL_BANKS[BANKITER]);
	PATCHITER = 0;
	dx7.setPatch(CUR_BANK[PATCHITER]);
log(PATCHITER, LIB.patches[PATCHITER]);
}
else keyboardDown(e, midikeys.keyDown);
};
const onkeyup = (e)=>{
	keyboardUp(e, midikeys.keyUp);
};

const getbank = ()=>{
	return new Promise(async(Y,N)=>{
		Y(await LIB.load(ALL_BANKS[BANKITER]));
	});
};

const start = async()=>{
let rv = await fetch('/_getdir?path=root/code/mods/av/synth/dx7/presets');
log(await rv.json());


await DX7.importScripts(ctx);
dx7 = new DX7(ctx);
dx7.connect(ctx.destination);
LIB = new DX7Library()
initGUI(LIB);
//let rv = await LIB.load("steinber.syx");
//CUR_BANK = await LIB.load(ALL_BANKS[BANKITER]+".syx");
CUR_BANK = await getbank();
//log(rv);
dx7.setPatch(CUR_BANK[PATCHITER]);
log(PATCHITER, LIB.patches[PATCHITER]);
//log(ALL_BANKS);

this.onkeydown = onkeydown;
this.onkeyup = onkeyup;

};


start();
}


